### ISSUE TITLE
Lab 4 says "..next exercise, will implement checkout logic.." but doesn't

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#1]
# Lab/Module: 04
## Description of issue
note says "..next exercise, will implement checkout logic.." but the next exercise is clean up

![image](https://user-images.githubusercontent.com/12022944/72656706-132c6700-3952-11ea-8ec8-51fd9370061d.png)

need to update note or add exercise to implement checkout

**Comment by seesharprun** [comment]
Good catch.

These are shorter labs than AZ-203 and are all designed to be completed by students within a 45-minute block.

We removed the checkout portion of the lab to squeeze this complex lab within the time limit. This will be updated ASAP.

**Comment by seesharprun** [comment]
Again, thanks for the heads up.
