### ISSUE TITLE
Migrating builds from Azure DevOps to GitHub Actions

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#101]
This is in very early stages, but it's been difficult to manage automated builds across two distinct platforms. I'm proposing to move our build pipelines to run natively in GitHub.

A couple of advantages:
- We can create high visibility PR builds so you know if your changes "break the build"
- You can track what release includes your PRs
- You can recreate the build in your own fork of the repo

Again, early discussion phase.

**Comment by tibor19** [comment]
I think this is a good idea!  Let me know if you need help with that.

**Comment by seesharprun** [comment]
The engineering effort wouldn't be extensive, we already have the Docker container image available as a public image in [microsoftlearning/docker-build](https://github.com/MicrosoftLearning/Docker-Build). Our pipelines are already in the repo, so it would be minor changes.

The biggest reason to open this up for discussion is to see if there's any considerations we missed in the early planning phase.

**Comment by tiagocostapt** [comment]
I have checked and I really don't see why we could face issues with this move. Happy to help if you need! Just PM me.

**Comment by seesharprun** [comment]
This is still in an early discussion/planning phase. This would be a break from how other repos in this org manage builds. Will update everyone as the planning moves forward.

**Comment by seesharprun** [comment]
While this issue is closed, we can still discuss the topic here. If an action item needs to be taken, we will reopen the issue.
