### ISSUE TITLE
Outdated Dockerfile

### ISSUE THREAD

**Issue by pdtit** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#103]
# Module: 05
#### Step: 03

The Dockerfile in the regular lab is still referencing dotnet 2.2, which fails the build; should be updated to 3.1 

(is mentioned correctly in the lab guide with answer key though)

Fix: 
# Start using the .NET Core 3.1 SDK container image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

instead of
# Start using the .NET Core 2.2 SDK container image
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine AS build

**Comment by seesharprun** [comment]
Yikes! good catch. Resolved in 3281e72.
