### ISSUE TITLE
Azure Cloud Shell Rollback

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#104]
Looks like the version of Azure Cloud Shell with .NET Core 3.1 was released too early. Cloud Shell has [now been rolled back to 2.2](https://twitter.com/snuffling/status/1298268571240259586).

I will need to rollback the changes made in #100 and #103.

**Comment by seesharprun** [comment]
Tagging @molenaar and @pdtit

**Comment by seesharprun** [comment]
![image](https://user-images.githubusercontent.com/5067401/91212414-2bc9e000-e6de-11ea-801b-850f9a8a739d.png)

**Comment by seesharprun** [comment]
Rollback is completed. Fix is available in latest release. Thanks for your patience!

**Comment by hjnowakowski** [comment]
Hi @seesharprun, I was doing the labs today and I got an error when trying to upload my image to the registry (due to versions not matching). Since the 3.1 seems to be the default version now, I'd suggest to de-rollback and use 3.1 in the Dockerfile 😉
