### ISSUE TITLE
Introduction of Event Grid System Topics 'breaks' Lab 10.

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#106]
# Module: 10
#### Step: 03

With the introduction of Event Grid System Topics, Event Grid Topics no longer show up in the search results when you create a new resource and type "Event Grid" in the dialog. Only when you type "Event Grid Topic" in the search dialog, will Event Grid Topics show up.

This should be included in the instructions. Step 3 should be modified from:

_In the search box, enter **Event Grid**, and then select Enter._

To:

_In the search box, enter **Event Grid Topic**, and then select Enter._

Alternatively, we can modify to lab to use Event Grid System Topics.

**Comment by seesharprun** [comment]
I updated the lab to have the user search for **Event Grid Topic**.
