### ISSUE TITLE
Wrong steps or maybe not entirely clear in the Instructions.

### ISSUE THREAD

**Issue by EsdinDev** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#108]
# Module: Instructions
#### Step: 02

Description of issue

You need to import the database to Azure Storage Account. On the step 2, you need to select as "Storage account" the value "polystor[yourname]**" but you can select this value, you need to navigate until you select the bacpac file.

Repro steps:

Follow the steps of the Module.

[Link](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_04_lab.md#task-3-import-an-sql-database)

**Comment by seesharprun** [comment]
I have ran through the instructions again and validated that they work as intended.

Here's the expected order and results:

1. In **Exercise 1 | Task 2**, you create a new Azure SQL Databases "server resource." This is distinct from a database resource and is done on purpose so students have practical hands-on experience managing them seperately.
2. In **Exercise 1 | Task 4**, you create an Azure Storage resource.
3. In **Exercise 2 | Task 2**, you upload the *.bacpac file from your Allfiles folder to Azure Storage as a blob.
4. In **Exercise 2 | Task 3**, you import the *.bacpac file from Azure Storage to the Azure SQL Database "server" and it will create a new database resource.

The lab instructions explain this only at a high level. The answer key gives step-by-step instructions.
