### ISSUE TITLE
Storage demo is using old version of the Azure SDK

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#109]
# Module: 3
## Demo: Using the Azure Blob storage client library for .NET v11

Description of issue
The demo is using v11 of `Microsoft.Azure.Storage.Blob`. This should be updated to the new version v12, `Azure.Storage.Blobs`. From the NuGet package description:  
> This library has been replaced by the following new Azure SDKs. You can read about the new Azure SDKs at https://aka.ms/azsdkvalueprop.

The lab has been updated to use the new version, but the demo is still using the old version. This is good reason to move the demos to GitHub #19

**Comment by seesharprun** [comment]
Officially demo issues and support tickets should be opened here: <https://trainingsupport.microsoft.com/tcmct/forum>.

**Comment by christiannagel** [comment]
Thanks for the information on the support tickets.
However, I'm not sure the support tickets would help with the next iteration of updates for this course content . The sample is still working as it is - it's just using an old syntax from the old library. As mentioned, the labs have been updated, but the demos and slides not.

If someone is interested, I've cloned the GitHub repo and created a *demos* branch where I put into the source code for the v11 storage client app and a first update to a new v12 version:
https://github.com/christiannagel/AZ-204-DevelopingSolutionsforMicrosoftAzure/tree/demos/Allfiles/Demos/03

**Comment by seesharprun** [comment]
Unfortunately, I cannot fix demos here. Officially demo issues and support tickets should be opened here: https://trainingsupport.microsoft.com/tcmct/forum. This will get the attention of the individual who maintains demos for this course.
