### ISSUE TITLE
Module 10, demo: az group deployment is deprecated

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#111]
# Module: 10, Develop event-based solutions
### Task: Create a message endpoint

The task uses the command `az group deployment create`

There's a warning using this command:
> This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

With the next iteration of the course updates (before the command is removed), `az deployment group` should be used instead with this demo.

**Comment by seesharprun** [comment]
Unfortunately, I cannot fix demos here. Officially demo issues and support tickets should be opened here: https://trainingsupport.microsoft.com/tcmct/forum. This will get the attention of the individual who maintains demos for this course.
