### ISSUE TITLE
AZ-204_03_lab.md Ex 4 Task 2 Step 6 code incorrect

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#13]
# Module: 03
#### Step: 06

Description of issue
Code does not match Answer Key (See AK Ex 4 Task 2 Step 8):

await GetContainerAsync(serviceClient, newContainerName);

should be:

BlobContainerClient containerClient = await GetContainerAsync(serviceClient, newContainerName);

**Comment by seesharprun** [comment]
This was resolved in 8110f8b06d0e2d6ca9cb4a3ead01bc2c40347daf
