### ISSUE TITLE
not able to download

### ISSUE THREAD

**Issue by rajeevoncloud9** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#130]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
If you require MCT support, you can open a ticket here: https://trainingsupport.microsoft.com/tcmct/forum.

**Comment by rajeevoncloud9** [comment]
Why?

**Comment by seesharprun** [comment]
I was unclear on your issue. Are you saying that you are unable to download the lab instructions and Allfiles content? Or are you saying that you are unable to download the course trainer files?

You will need to open a MCT support ticket through the proper channels for support with downloading the course trainer files.

If you need to download the lab content, you can go to [this link](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/releases/latest). You will see two zip files with the latest version of the course files. An unofficial online-hosted version of the lab instructions are also available here: <https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/>

**Comment by rajeevoncloud9** [comment]
I am not able to reschedule my exam.
Please help.

**Comment by seesharprun** [comment]
If you have a certification exam question, you can get support here: https://trainingsupport.microsoft.com/mcp/forum.

This repository is only for lab content for Azure developer training content. We cannot help with certification exams here and have no visibility into that process.
