### ISSUE TITLE
Lab 4 Task 2 No longer representative of the end user Azure Portal

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#134]
# Module: 04
#### Step: 5e

Azure Pass - Sponsorship subs don't have access to (US) East US

Repro steps:

1. complete steps 1 to 8
2. observer validation error
3. Switch to Basic tab
4. change subscription to (US) South Central US
5. Review + create
6. observe validation succeeds

**Comment by seesharprun** [comment]
We will need to investigate this further.

**Comment by seesharprun** [comment]
@JeffKoMS let's validate this ASAP

**Comment by loaderladdy** [comment]
Am currently doing the AZ500 course and this happened again yesterday, to our course trainer. It's not consistent, and I assume it's something to do with the way the Azure Pass is set up, but that's just my guess. 

When I say it's not consistent, using East US works for most Lab modules, just not all of them.

**Comment by cdanvergara** [comment]
I got the same error during AZ-204 today while selecting East US as the instructions:
[#](url
![image](https://user-images.githubusercontent.com/6410720/105896730-2d793600-5fe5-11eb-9867-f86108a0c982.png)
)
Works with South Central US .
We need to fix this urgently!

**Comment by christiannagel** [comment]
I don't think there's a fix for this. It might be working today with the East US region. https://aka.ms/sqlcapacity shows that Azure Pass is available with the East US region. It can happen any time that a region does not have enough capacity, and Azure Pass is not a high priority. It should be possible for the students to select another region.

Once in a workshop some students succeeded creating a resource in a specific region, and all the students that were late failed. The students didn't have an issue selecting a different region.

**Comment by JeffKoMS** [comment]
I'm going to close this issue for now and if it pops back up again it looks like the investigation would be in to Azure Pass or capacity in a region.
