### ISSUE TITLE
using .NET Core 2.2 SDK in Lab 5 throws an error

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#136]
# Module: 05
#### Step: 02:08 +05:03

Description of issue: 

Code at 02:08 specifies "# Start using the .NET Core 2.2 SDK container image
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine AS build"  This fails at 05:03.

Substitute old code with "# Start using the .NET Core 3.1 SDK container image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1  AS build"

Repro steps:

1. follow instructions for Tasks 2 & 5
2. observer the error relating to .NET Core SDK version
3. replace code at Task 02 step 08 with new code
4. observe the build completes

**Comment by seesharprun** [comment]
Resolved in ee5dc87
