### ISSUE TITLE
App Registration -> Authentication - "Default client type" option re-worded

### ISSUE THREAD

**Issue by blueghostuk** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#138]
# Module 06: Implement user authentication and authorization
##### Step: 01

Description of issue

There is no "Default client type" option under the "Authentication" section.

I believe it is now "Allow public client flows" - note I have switched this to "Yes" from the default "No"

![image](https://user-images.githubusercontent.com/1785586/102251196-66a98b00-3efc-11eb-9c39-a41672d12ea4.png)

Point of reference - this docs page shows the old wording - https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration (raised docs issue here - https://github.com/MicrosoftDocs/azure-docs/issues/67751)

**Comment by seesharprun** [comment]
This is resolved in #124.
