### ISSUE TITLE
Module 06, Lab 06, Exercise 01, Task 03, Step 01, misworded label to enable client flows

### ISSUE THREAD

**Issue by naulacambra** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#146]
# Module 06: Implement user authentication and authorization 
#### Step: 01

Misworded label to enable public client flows

Current:
> 1. Find the **Authentication** section of the **graphapp** application registration blade, and then enable the **Default client type** option.

Correction:
> 1. Find the **Authentication** section of the **graphapp** application registration blade, and then enable the **Allow public client flows** option.

**Comment by seesharprun** [comment]
This is resolved in #124.
