### ISSUE TITLE
Module 07, Lab 07, Exercise 03, Task 03, Step 14, misworded file names to be saved

### ISSUE THREAD

**Issue by naulacambra** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#147]
# Module 07: Implement secure cloud solutions
#### Step: 14

Misworded the file that has to be saved.

Current
> 14. **Save** the **Echo.cs** file.

Correction
> 14. **Save** the **FileParser.cs** file.
---
#### Step: 05

Misworded the file that has to be saved.

Current
> 5. **Save** the **Echo.cs** file.

Correction
> 5. **Save** the **FileParser.cs** file.

**Comment by seesharprun** [comment]
Resolved in #119 and #120.
