### ISSUE TITLE
How to access windows 10 lab vm

### ISSUE THREAD

**Issue by jbollman7** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#149]
# Module: 01
### Task: 01

Description of issue
`
Instructions
Before you start
Sign in to the lab virtual machine

Ensure that you’re signed in to your Windows 10 virtual machine by using the following credentials:

    Username: Admin

    Password: Pa55w.rd
`
Are the labs described in this github repo, found on microsoft-learn training paths?  I cannot find the same course material on microsoft-learn.

Where would I find the lab vm with all the resources on it(lab-materials, files to upload)?

Thanks

**Comment by EricCote** [comment]
Easiest solution: The lab VM is provided when you register to a scheduled course with your local Microsoft Learning Partner.  See the full list of Microsoft Learning Partners here: https://docs.microsoft.com/learn/certifications/partners .

Hard solution: The lab VM can be created by yourself. It's not as convenient as having one provided by a training partner. You can even use your own Azure subscription.  It's a regular Windows 10. You simply need to add some apps. Here is the list of software that needs to be installed on the vm: https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/lab.md

Eric Cote, Microsoft Certified Trainer (MCT)

**Comment by seesharprun** [comment]
The labs in this repository are exclusive to official Microsoft course deliveries. Those deliveries include a pre-build lab environment.

@EricCote is right, you can build the lab VM yourself using the ``lab.md`` file.
