### ISSUE TITLE
AZ-204_05_lab.md Ex 3 Task 1 Step 3 Note should be changed to match AK

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#15]
# Module: 05
#### Step: 03

Description of issue
Note should be changed to match AK
"Note:   Your changes automatically save." should be "Note: Make sure you save the update"
--

**Comment by seesharprun** [comment]
It looks like the entire interface for creating a container instance has just been updated to a wizard. This will require a deeper rewrite of the lab instructions.

**Comment by begler1** [comment]
Correct. This is a quick fix to keep the current instruction working until the lab can be rewritten. We have a class running next week.

**Comment by seesharprun** [comment]
b0a72726d7d6ec97d8ebfc814c4ca1d5793f5778 updated the instructions to fix this bug.
