### ISSUE TITLE
Azure-slice user cannot register providers

### ISSUE THREAD

**Issue by EricCote** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#155]
# Lab: 13
#### Step: 1.vii  (7)

The step asks you to type the following in a Cloud Shell command-line:

`
az provider register --namespace Microsoft.CDN
`

It then returns an error message saying that the Azure-slice user doesn't have sufficient permissions to register providers.

**Comment by JeffKoMS** [comment]
@EricCote  It's up to each of the ALH providers to adjust lab steps to meet the needs of their environments. The lab steps are designed and tested against a typical Azure Pass and run on the VMs provided to the students.
