### ISSUE TITLE
Module 2 Exercise isn't really a Blog Trigger

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#158]
# Module: 02
#### Step: 00

Description of issue
Why create a Blog Trigger and transform it back into a Http-triggered function?
You would expect that uploading a new settings.json file, it should trigger and log it. Now its just a similar function like exerise 3.

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
I just merged a PR (#183) that changes from a Blob Trigger to a HTTP Trigger function.

Some background on why this existed originally:

> When we first designed the lab, there wasn't an easy way to register extensions. If you created a HTTP-triggered function, you would get a build error saying that the Blob output attribute could not be found. The original lab bypassed this by having you create a Blob-triggered function that included attributes for HTTP-input and Blob-output. I updated the lab to be a HTTP-triggered function, and then add a step to register the Azure Storage extensions so it can find the Blob output attribute.
