### ISSUE TITLE
AZ-204_05_lab.md Ex 3 Task 3 Step 3 Image source must be set correctly

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#16]
# Module: 05
#### Step: 03

Description of issue
Instructions assume that **Image source** is set to **Docker Hub or other registry** otherwise specified fields do not appear. (same should be set in AK)

**Comment by seesharprun** [comment]
It looks like the entire interface for creating a container instance has just been updated to a wizard. This will require a deeper rewrite of the lab instructions.

**Comment by begler1** [comment]
Correct. However, my suggestion above is a quick fix that will keep the existing instructions working until the lab can be rewritten.

**Comment by seesharprun** [comment]
b0a72726d7d6ec97d8ebfc814c4ca1d5793f5778 updated the instructions to fix this bug.
