### ISSUE TITLE
The runtime stack for creating functions is now simply .NET not .NET Core

### ISSUE THREAD

**Issue by asos-andrewgoad** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#168]
# Module: 07
#### Step: 01

Description of issue

The runtime stack for creating functions is now just `.NET` rather than `.NET Core`

Repro steps:

1. Create a new function app https://portal.azure.com/#create/Microsoft.FunctionApp
2. On `Basics` tab, select the Runtime stack `.NET`

![image](https://user-images.githubusercontent.com/42029884/109141605-d2f30700-7755-11eb-911a-ff6742751616.png)

**Comment by LodsCory** [comment]
Pull Request submitted. https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/pull/169

**Comment by JeffKoMS** [comment]
Thanks, fixed!
