### ISSUE TITLE
AZ CLI commands for Bash vs PowerShell Cloud Shell

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#172]
# Module: 06
#### Step: 08

Description of issue
Lab steps ask the student to setup the Cloud Shell for PowerShell, but then show AZ CLI commands for Bash.
The lab steps that create variables do not prefix the variables with a dollar sign ($), but the Cloud Shell is left in PowerShell mode after setup.

The AZ CLI commands either need to include the $ for variables, or ask the student to switch to the Bash shell.
Ex 1: Task 4: Step 8:
For Bash: 
   ipAddress=$(az vm list-ip-addresses ...
For PowerShell:
   $ipAddress=$(az vm list-ip-addresses ...

Repro steps:

1.
1.
1.

**Comment by AustinP00** [comment]
![image](https://user-images.githubusercontent.com/53233868/110915601-d950b980-82e5-11eb-9356-09a70ef1ab76.png)

this seems to already match the solution given to the issue​

**Comment by microsmith** [comment]
AustinP00, Unless they are in the Cloud Shell in PowerShell mode.

**Comment by robfoulkrod** [comment]
The Lab file specifies to open the shell in Bash. The Lab Answer Key does not.  I think we would want to be more specific in the LAK as to the correct shell instead of trying to write bi-shell instructions.

**Comment by seesharprun** [comment]
All of the lab instructions are written using the Bash version of the shell.

In any lab where you could potentially first configure the Azure Cloud Shell, we have instructions that say:

> A dialog box prompts you to create a new storage account to begin using the shell. Accept the default settings, and then select **Create storage**.

**That's not specific enough.**

In #185, we updated the steps to say:

> A dialog box prompts you to configure the shell. Select **Bash**, review the selected subscription, and then select **Create storage**.

I think that should work for specificity.
