### ISSUE TITLE
Module 09 required administrator email address

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#173]
# Module: 09
#### Step: 06

Description of issue

Lab says: "Leave the Administrator email text box set to its default value."
The field is blank, and is required (*). What email should be entered here. (A dummy works.)

Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
@microsmith Thanks! We'll take a look at it this week.

**Comment by seesharprun** [comment]
I added the text "If this field is empty, you can enter any non-working email address." to the API Management lab in #186
