### ISSUE TITLE
XtremeLabs: AZ-204T00-A-CEP [AZ-204T00-A-CEP] : Please an an option for PowerShell

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#177]
# Module: Module 02: Implement Azure Functions
#### Step: 3: Azure Functions Core Tools to create a new local Azure Functions project

One is able to select languages between C# and Visual Basic for the Az-204 exam but not **`PowerShell`**.  Is it in the roadmap to add PowerShell as a language of choice? Could you add an option do do the labs in PowerShell instead of CLI?

**Comment by JeffKoMS** [comment]
@Ayanmullick We probably aren't going to try and add a lot of different tool/language options to the official lab steps since maintenance would become a huge issue. You might want to log this request with Xtreme to see if they might want to add it to their implementation.

**Comment by Ayanmullick** [comment]
@JeffKoMS, XtremeLabs Senior Support Technician Nick B. confirmed thru support ticket number 12338 that they would need the specific PowerShell steps updated by the course author on GitHub to update the lab manual.

**Comment by JeffKoMS** [comment]
@Ayanmullick If Xtreme gets enough requests they may take that on, but as I mentioned earlier maintaining multiple language options for the labs would create maintenance issues for us at this time. I'll close this for now, but feel free to ping again in the future if this is an issue for a large number of your students.
