### ISSUE TITLE
Should demos be stored in GitHub?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#19]
Are the demos going to be maintained in this repo? They are currently in Skillpipe. My understanding was that all instructions (labs + demos) for new courses are to be hosted in GitHub.

**Comment by seesharprun** [comment]
I don't know of any plans to put the demos in this repository. Where did you hear that all demos will be hosted on GitHub?

Pinging the course's author for insight @JeffKoMS

**Comment by JeffKoMS** [comment]
No current plans to put the demos in GitHub. Certainly something we can take in to consideration. Can you let me know who's setting that expectation?

**Comment by VitalyMCT** [comment]
Well, it would certainly be beneficial to have any fast-changing instructions hosted on a platform  that supports rapid change. Same reason Microsoft moved lab instructions from Skillpipe to GitHub.

Take a look at https://github.com/MicrosoftLearning/20778-Analyzing-Data-with-Power-BI for an example. Old (B) version used to have labs + demos in Skillpipe. New (C) version has both in GitHub and that works much better.

I personally can't think of any significant pros to _not_ put instructions in GitHub. As a related aside, as we all know, the Azure docs (docs.microsoft.com) have also recently been put into GitHub.

**Comment by seesharprun** [comment]
I can’t speak for Microsoft but I have observed that the decision to put demo instructions on GitHub is on a course-by-course basis. For example, AZ-220 and AZ-103 do not store demo instructions on GitHub.

I also want to call out that docs.microsoft.com has been on GitHub since it’s inception four years ago. The first repo in the MicrosoftLearning org is more than five years old.

**Comment by JeffKoMS** [comment]
Good points. I'll start looking at that next week.

________________________________

**Comment by VitalyMCT** [comment]
@JeffKoMS, would it be possible to get an update?

**Comment by WigF1** [comment]
Given the cadency of changes, I agree it would make an infinite amount of sense to have the Demos in the repo too.

**Comment by seesharprun** [comment]
While this issue is closed, we can still discuss the topic here. If an action item needs to be taken, we will reopen the issue.

**Comment by VitalyMCT** [comment]
@seesharprun, what's the issue's resolution? I've reviewed this thread and am confused as to the reason it's being closed.

The last action-related comment was from @JeffKoMS:

> Good points. I'll start looking at that next week.

There are no actions mentioned thereafter.

**Comment by seesharprun** [comment]
I was closing inactive threads this week. I didn't see any action from the course owner[s], so I closed this thread until they post again.

**Comment by WigF1** [comment]
It would be nice to leave it open so that the course owner[s] have some visibility.

As mentioned, for the same reason we have the lab steps in GitHub, we should have the demos in too.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ecaha** [comment]
Completely agree on to have demos on Github. Let's say even in more ready to go way as well. For example all RG names, resource names, etc. prefilled. I did it for myself, therefore I have all demo scripts copy & paste ready. Maybe we can utilize GitHub variables for markdown files to introduce a unique prefix. Then you can just fork repo, substitute variable and you have ready to go version of all demos.

Yes, I am very lazy, but it definitely helps how the training flows.

**Comment by christiannagel** [comment]
I'm also for adding the demos to GitHub. The [readme](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/readme.md#how-do-i-contribute) file mentions:

> You can submit bugs, changes, improvement and ideas. Find a new Azure feature before we have? **Submit a new demo!**

How to submit a new demo if the demos are not part of the repo?

Because several demos include some source code, many trainers will have there own repos for the demos. To combine the effort it would be great to have the demos here in this repo.

**Comment by seesharprun** [comment]
Good catch! That readme is template language that is used in almost all repos within this org.

This issue is still open until a business decision is made on whether to include demos or not. I will keep echoing the messaging from these comments.

**Comment by seesharprun** [comment]
This issue is now closed as I haven't heard anything on moving demos to GitHub. If that changes, I will reopen the issue.
