### ISSUE TITLE
Microsoft.Sql resource provider

### ISSUE THREAD

**Issue by bakirnajjar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#190]
# Module: 04
#### Step: 01

Description of issue
The Microsoft.Sql resource provider is not registered most of the time with the learners which leads to error.

Repro steps:
1. Open Cloud Shell
2. Run this command to register it: az provider register --namespace Microsoft.Sql
3. Run this command to check it: az provider show --namespace Microsoft.Sql

**Comment by seesharprun** [comment]
@JeffKoMS, we may need to grab an Azure Pass and verify this behavior.

**Comment by tiagocostapt** [comment]
I might give some feedback on these. I also have the same issue in several classes that we still use the Azure Passes. 
Maybe add some instruction to make sure the provider is registered and if not to register it? Even maybe just a PS script, this way it's resistant to Portal UI changes. 
It's not an issue when we use one of the Lab Hosters.

**Comment by seesharprun** [comment]
The list of registered providers is particularly variable and changes on a regular basis.

Step one is to check a current Azure Pass.

Step two is to determine if adding registration instructions is a one-time change or a change that needs to be made to every lab.

**Comment by JeffKoMS** [comment]
@seesharprun I'll ask for an Azure Pass to be sent your way so you can test this out.

**Comment by seesharprun** [comment]
Using a fresh Azure Pass, I queried my provider list and saw ``Microsoft.Sql``. I also ran ``az provider show --namespace Microsoft.Sql`` and got a non-empty response. I did notice that the provider list was in non alphabetical order by default, so you can apply a sort using this query: ``az provider list --query "sort_by([].{Name:namespace}, &Name)" --output table``:

![image](https://user-images.githubusercontent.com/5067401/113887043-26159c00-978f-11eb-97ed-4ab2be26cb68.png)

**Comment by erickamor** [comment]
Azure Pass subscriptions are also prevented from creating SQL DB server in EastUS - should edit to recommend trying other regions.

**Comment by seesharprun** [comment]
I just used an Azure Pass to create a ``Microsoft.Sql/servers`` resource and a ``Microsoft.Sql/servers/databases`` resource with the logical server deployed to **East US**.

Are you having trouble with this?

### Screenshots

1. ![image](https://user-images.githubusercontent.com/5067401/114620328-7736fb80-9c79-11eb-90f7-a79f78e8e442.png)
1. ![image](https://user-images.githubusercontent.com/5067401/114620339-7a31ec00-9c79-11eb-87e4-60619106528b.png)
1. ![image](https://user-images.githubusercontent.com/5067401/114620351-8158fa00-9c79-11eb-84dc-d9bfe97d77b8.png)
1. ![image](https://user-images.githubusercontent.com/5067401/114620365-861dae00-9c79-11eb-8c8f-8a3d6e3d9b96.png)
1. ![image](https://user-images.githubusercontent.com/5067401/114620382-8a49cb80-9c79-11eb-8a59-2a8c8d0077e0.png)
1. ![image](https://user-images.githubusercontent.com/5067401/114620537-ab122100-9c79-11eb-97a1-0a2a638e1c8f.png)

**Comment by erickamor** [comment]
Interesting - when I just tried received this message which is what I've seen consistently/recently.
![image](https://user-images.githubusercontent.com/37192354/114647546-45d72380-9cab-11eb-8ae6-87c6088ce248.png)

Then when retrying (same region) was successful.

**Comment by seesharprun** [comment]
That is odd

**Comment by seesharprun** [comment]
Is any other MCT having this issue?

**Comment by ElaMark** [comment]
Yes. We had this issue this week. People created the SQL Server in SouthCentral US instead.

**Comment by mkennten** [comment]
My students experience the issue with East US and other regions this week, too.

**Comment by christiannagel** [comment]
Today I had an issue creating SQL Server in West Europe using a Visual Studio subscription. Successful with North Europe. Later my students - using an Azure Pass - couldn't create SQL Server in North and in West Europe - but succeeded in South Central US.

It's ok as long as there's success in one region :-)

**Comment by seesharprun** [comment]
@JeffKoMS, this should be escalated to the person in charge of managing Azure Passes. I am going to close this issue since it's out of scope and encourage any MCT to open a new issue if they are unable to deploy SQL server resources to East US.

**Comment by bakirnajjar** [comment]
The solution is very simple which is to register the Microsoft.Sql provider. We can just add this command in the Lab's steps:
az provider register --namespace Microsoft.Sql
