### ISSUE TITLE
Change Allfiles\labs\10 to 9

### ISSUE THREAD

**Issue by bakirnajjar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#191]
# Module: 09
#### Step: 01

Description of issue
Using Visual Studio Code, open the Allfiles (F):\Allfiles\Labs\10\Starter\EventPublisher folder.

The Lab folder should be 09 not 10. Thanks!

**Comment by seesharprun** [comment]
This should be corrected in 35033a1
