### ISSUE TITLE
Search the Marketplace for "container instances" not "container instance"

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#193]
# Module: 05
##### Step: 03

Description of issue
When looking for "container instance" as written in the instructions the market place doesn't show the "container instances" service. Only when you search for "container instances" they will show up.

Repro steps:

1. In the Azure portal’s navigation pane, select the Create a resource link.
1. From the New blade, find the Search the Marketplace text box above the list of featured services.
1. In the search box, enter Container instance, and then select Enter.

**Comment by seesharprun** [comment]
This should now be updated to the search term "container instances" in 9da9e32.
