### ISSUE TITLE
Storage Explorer UI has changed, instructions need update

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#197]
# Module: 10
##### Step: 16
Description of issue
The UI has changed in the Storage Explorer App and the instructions don't match anymore.

For example:
Now: "In the Expires in text box, enter the value 12."
Should be: "In the Expire in text box, enter the value 12."

Now: "Ensure that the Encode message body in Base 64 check box isn’t selected."
Should be: "Ensure that UTF8 is selected in the Encoding drop-down."

**Comment by seesharprun** [comment]
Has the Storage Explorer app been updated? I checked the lab VM and it's still running an older version of the Storage Explorer app.

**Comment by seesharprun** [comment]
If you run into this issue again, can you send a screenshot of the incorrect UI label and share the version number of the Storage Explorer UI. The team wants to confirm that you are running the same version of the Storage Explorer that was installed on the lab VM.
