### ISSUE TITLE
Update command to reference the current Lab files

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#198]
# Module: 11
##### Step: 11

Replace
`cd F:\Allfiles\Labs\12\Starter\`
With
`cd F:\Allfiles\Labs\11\Starter\`

# Module: 12
##### Step: 07.b and 13.b

Replace
`Allfiles (F):\Allfiles\Labs\13\Starter`
With
`Allfiles (F):\Allfiles\Labs\12\Starter`

**Comment by seesharprun** [comment]
This is resolved in c6b120b
