### ISSUE TITLE
Lab 02: HTTP Trigger Template name change

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#2]
# [Lab/Module: 02](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_02_lab.md) Implement task processing logic by using Azure Functions
#### Step: 02
>#### Description of issue: instruction, `Template: HTTP trigger`, doesn't match UI
>![image](https://user-images.githubusercontent.com/12022944/72917353-8a6a4e00-3cf8-11ea-9b61-2efbd80e2478.png)
>#### Proposed Solution: Change to - `Template: Webhook + API (HTTP Trigger)`

**Comment by seesharprun** [comment]
You are correct, in the high-level instructions they wouldn't know to select "Webhook + API" to get an HTTP trigger.

**Comment by eric-camplin** [comment]
but seems I can go to the entry point again and get `HTTP Trigger`... the quick start view hides it.  The Quick start template also makes it hard to name and set authorization level.
![image](https://user-images.githubusercontent.com/12022944/72919533-7cb6c780-3cfc-11ea-8b67-718d8ac3240b.png)
 
So needs some other instruction...  but my suggestion isn't better

**Comment by seesharprun** [comment]
We have a functional test pass in two weeks. I wonder if I should wait to see if those testers file a bug and come up with a resolution then. We can always reopen this issue.
