### ISSUE TITLE
Module 6 - Labs are in folder 07

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#20]
# Module: 06
#### Step: 03

Description of issue
This is module 6 and you have to select folder 07 in All Files.

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
It looks like Labs 06 & 07 had their Allfiles swapped. This is fixed in 0f5710daa98dc7b334fb34d8bbbe177ed382c3c9
