### ISSUE TITLE
Lab 03 - Blob Storage 

### ISSUE THREAD

**Issue by MrPeanutButta** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#216]
# Module: 03
#### Step: 01

Description of issue

Instructions are incorrect. There is no selection for RA-GRS. Have to select GRS and check box for enabling read-access (RA-GRS).

Repro steps:
![image](https://user-images.githubusercontent.com/2099033/116293545-e4539200-a74b-11eb-9dbc-10c533dc4fb0.png)

**Comment by mkennten** [comment]
The UI has changed and the instructions should be updated - for a quick solution you could let the students use the "legacy storage account type" link.

**Comment by Sidney-Andrews** [comment]
The UI has changed, the current PRs to resolve this are all being evaluated right now.

**Comment by wilsonmar** [comment]
Some storage types don't show for some regions.

**Comment by seesharprun** [comment]
This is resolved in 657e4b0
