### ISSUE TITLE
Lab 7: Fix/clarify Step

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#217]
# Module: 7
#### Step: 3 & 4

**Description of issue**: some steps should be fixed/clarified. Many students jump in the Application Insights (same name as azure function and it takes less time to be created) and get lost). Also task 4 should say "Function App" blade --> not "App Service"".

**Proposed change (I can create PR if  needed)**:

_3. From the **ConfidentialStack** blade, select the **securefunc[yourname]** function app  that you created earlier in this lab (not the Application Insights, which has the same name and takes less time to be created ).
4. From the **Function App** blade, select the **Identity** option from the **Settings** section._

**Comment by seesharprun** [comment]
This is resolved in 0819da484b79f4e825b5bcaea865e3c63256a0a8
