### ISSUE TITLE
Lab 8 : many mentions of Web App Blade should be App Service

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#218]
# Module: 8
#### Step: 00

Description of issue:

Many mentions of Web App Blade should be App Service, only in creation is "called" Web App, once created the blade shows "App Service" under the name of the resource. Students get confused.

**I can provide PR if needed.**

**Comment by seesharprun** [comment]
Resolved in f6755d4
