### ISSUE TITLE
Lab 01: Note should not state to expect to see 404 error

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#219]
# Module: 01
#### Step: 05

The note states to expect a 404 error, but what shows is a placeholder website. This should be changed so that users are not waiting for an error that doesn't show up.

"Note: At this point, the web server at this URL will return a 404 error. You have not deployed any code to the Web App yet. You will deploy code to the Web App later in this lab."

**Comment by seesharprun** [comment]
This was resolved in a recent commit.
