### ISSUE TITLE
Lab 05: dotnet cmd using single hyphen

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#220]
# Module: 05
##### Step: 05

Description of issue
The dotnet command uses a single hyphen instead of double hyphen and the cmd fails.
dotnet new console –output . –name ipcheck

Should be:
dotnet new console --output . --name ipcheck

**Comment by seesharprun** [comment]
It looks like an error in Jekyll where it converts from a double hyphen to a single hyphen on publish. The source files were technically correct.

We made a publishing change in 5a7a7fd and it should be fixed.
