### ISSUE TITLE
Lab 7 Access Keys under Security, not Settings

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#227]
In Lab 7 step 12 says "From the Storage account blade, find the Settings section, and then select the Access keys link." However, Access Keys is under "Security + networking":
![Screen Shot 2021-05-17 at 2 34 03 PM](https://user-images.githubusercontent.com/300046/118553335-687eb100-b71d-11eb-9ada-5bebaf64d271.png)
![Screen Shot 2021-05-17 at 2 37 40 PM](https://user-images.githubusercontent.com/300046/118553372-759ba000-b71d-11eb-9925-8a8d2ac8e57d.png)

**Comment by seesharprun** [comment]
This is resolved in a series of recent pull requests.
