### ISSUE TITLE
Module 2 Endpoints not in settings > properties anymore 

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#228]
# Module: 02
#### Step: 13

Description of issue
The instructions say to go to the settings and get the primary endpoint but it has moved to Endpoints > Primary endpoint
Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
This is resolved in a series of recent pull requests.
