### ISSUE TITLE
03: containerClient is not defined in Exercise 4

### ISSUE THREAD

**Issue by bishrant** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#23]
# Module: 03
#### Step: 06

Description of issue
The variable mentioned in Step 6 'containerClient' is not defined in the steps above.

Repro steps:
Follow the manual listed at https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_03_lab.html without missing any steps.

See this for the actual line the error occurs:
![image](https://user-images.githubusercontent.com/4143738/78089771-f539a480-738d-11ea-8799-acf9aa9afdad.png)

**Comment by massimobonanni** [comment]
Yesterday I proposed a pull request to fix it.

**Comment by seesharprun** [comment]
This was resolved in 8110f8b06d0e2d6ca9cb4a3ead01bc2c40347daf
