### ISSUE TITLE
Lab 5, Exercise 2, Task 5 - az acr list returns an empty list prior to building any container images

### ISSUE THREAD

**Issue by justinlazarus** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#232]
# Module: AZ-204
#### Step: 00

Description of issue
- az acr list returns an empty list prior to building any container images
- I was able to run the build by specifying the container registry name directly
- slight confusion about storing the container registry name in a var for later use

**Comment by seesharprun** [comment]
This lab was tested this month and ``az acr list`` did successfully return a list of container registries. It is possible for this command to fail if the student moves forward with the lab before the ACR resource is deployed. This is called out in the lab instructions currently.

**Comment by kozchris** [comment]
I'm seeing the same issue. Specifying the RG is not working either. Container Registry exists and I can work with it in the portal. 

`chris@Azure:~$ az group exists --resource-group ContainerCompute
true
chris@Azure:~$ az acr list
[]
chris@Azure:~$ az acr list --resource-group ContainerCompute
[]`

**Comment by kozchris** [comment]
Timing issue apparently. It took 30 minutes but the results are returning now.
