### ISSUE TITLE
Lab12, Exercise 2, Task 5: Not able to create endpoint with Standard Akamai pricing tier

### ISSUE THREAD

**Issue by easyrepro** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#235]
Lab12, Exercise 2, Task 5: Not able to create endpoint with Standard Akamai pricing tier

![image](https://user-images.githubusercontent.com/60021145/119058875-0d022c80-b984-11eb-9dc0-e92ede4a0e19.png)

**Comment by seesharprun** [comment]
The lab now uses the "Standard Microsoft" pricing tier
