### ISSUE TITLE
Lab 7 : Publishing func azure functionapp fail

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#237]
# Module: 07
#### Step: 06

Description of issue : func azure functionapp publish securefuncmp returns error: Can't find app with name "securefuncmp"

Repro steps:

1. Create function
1. Try to publish
1.

**Comment by seesharprun** [comment]
When you tried to publish, did the name in the command match your function app name? can you provide a screenshot of your resource group and the command output?

**Comment by mpaione** [comment]
Kind of typo or something, this is working today. I don't now if due to I've used Azure function in VS Code to finally publish. I'll check in a brand new environment but you can close this issue as resolved . Thanks .
