### ISSUE TITLE
Lab 03: Retrieving Azure Storage resources - 

### ISSUE THREAD

**Issue by danfolkes** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#238]
# Module: AZ-204: DEVELOPING SOLUTIONS FOR MICROSOFT AZURE
#### Step: 07

Description of issue

Repro steps:

1. I think that you should add some code that will pull create a SAS url for the blob. that way the link will work on a private blob.

**Comment by seesharprun** [comment]
An earlier version of this lab had the students access a blob programmatically (Stream) and by a SAS URI from a private container.

I think that was stripped out to keep the lab under 45 minutes.

I highly recommend showing this off to students as a demo after the lab is done.
