### ISSUE TITLE
Storage Account UI updates

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#244]
# Module: 03
#### Step: 05

Description of issue
Storage Account creation wizard is updated. Defaults to general purpose v2. To create a v1 storage account you need to click on a link to the original creation wizard.

In LOD, the option RA-GRS is not available. Only GRS as the highest option.

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
These were updated recently in a series of pull requests.
