### ISSUE TITLE
recent changes broke the labs for az-204 - getting error

### ISSUE THREAD

**Issue by LTatGE** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#249]
# Module: All
#### Step: all

Description of issue
Labs in az-204 no longer works with removal of solution md. 

Getting the following error message : 

"Unable to retrieve content from https://raw.githubusercontent.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/master/Instructions/Labs/AZ-204_01_lab_ak.md"

Repro steps:
try running any Az-204 lab

**Comment by tiagocostapt** [comment]
You can find the file at - https://raw.githubusercontent.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/master/Instructions/Labs/AZ-204_lab_01.md

But why not using this page for all the instructions - https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/

**Comment by LTatGE** [comment]
@tiagocostapt - yes that is the workaround - but from a student experience standpoint, basically everyone is confused and has wasted a great deal of time ... and it also breaks the auto text input and we have to do a copy and past and then insert via clipboard insert ... basically the lab interface for lab on demand is now useless... these are all esi students including myself ... this is supposed to be a premium service... can someone look into restoring the lab on demand use otherwise what is the point in going thru LOD

**Comment by tiagocostapt** [comment]
@LTatGE , you have to open a support on Lab on demand. Not an issues here. 
Ask you Trainer to do it if he already didn't had done it.

**Comment by ZekeStarr** [comment]
@LTatGE and @tiagocostapt 

After seeing this, we (LODS) have updated the references in our lab instruction to point to the new naming convention.

**Comment by AndrewConniff** [comment]
> @LTatGE and @tiagocostapt
> 
> After seeing this, we (LODS) have updated the references in our lab instruction to point to the new naming convention.

Ok I will see if we get them - the url it was trying to hit was def. a 404

**Comment by barkebark** [comment]
I'm also in this course right now. Confirmed it's back up.

**Comment by seesharprun** [comment]
Everyone, the high-level lab instructions were removed this week and only the detailed instructions renamed. The files were also renamed.

It looks like this change broke the references for LODS which were fixed pretty quickly.

Pinging @JeffKoMS for visibility.
