### ISSUE TITLE
Lab06 - Exercise 3 - 401 Unauthorized

### ISSUE THREAD

**Issue by silverio27** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#256]
#### Step: 02

A message error 401 unauthorized appears.

I'm solve this with additional step:
![msal](https://user-images.githubusercontent.com/59040502/122777825-c7869700-d282-11eb-972a-5694d4b06607.png)

**Comment by seesharprun** [comment]
I just checked the instructions online and it seems like this is called out already in Exercise 1 Task 3. Please reopen if this is incorrect on your end.
