### ISSUE TITLE
Command in Step 03 of Task 05(Exercise 02 - Lab 05 ) failing with an error

### ISSUE THREAD

**Issue by gauravjoshi0305** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#261]
# Module: 05
#### Step: 03

Description of issue
While performing Step 03 of Task 05(Exercise 02), the command "**az acr build --registry $acrName --image ipcheck:latest .**" fails with an error message : "**'NoneType' object is not callable**"

Repro steps:

1. Lab steps of Task 05(Exercise 02). The command to build the container image fails : 
     az acr build --registry $acrName --image ipcheck:latest .

**Comment by yashints** [comment]
This gets resolved by reverting your az cli back to version 2.25.0

**Comment by gauravjoshi0305** [comment]
Is this possible for cloud shell also as the labs is being performed using cloud shell(as per the instructions).

**Comment by WigF1** [comment]
Yes, Guarav.

See #269 for more info. If you run 'pip install azure-cli' it will resolve the issue.

**Comment by gauravjoshi0305** [comment]
This worked. Thanks 👍
