### ISSUE TITLE
Module 12 CDN Lab

### ISSUE THREAD

**Issue by bakirnajjar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#262]
# Module: Module 12: Integrate caching and content delivery within solutions
## Lab/Demo: 12
Exercise 02 
#### Step: 00

Description of issue
In the Pricing tier drop-down list, select Standard Microsoft. 

Standard Microsoft doesn't fit with the rest of instructions. We have to select Standard Akamai to be capable to choose Video streaming optimization or other optimizations.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
