### ISSUE TITLE
Lab 04: Cosmos does not exist in East US

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#266]
# Module: 00
#### Step: 00

Description of issue
Create Cosmos - Cosmos cannot be created in East US - needed to be created elsewhere
Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
I think this was just a temporary issue with the Azure pass.
