### ISSUE TITLE
Lab 05 --  if you get error: 'NameType' object is not callable

### ISSUE THREAD

**Issue by dqzhu** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#269]
# Module: 05
#### Step: 03

Description of issue:  

if you get error: 'NameType' object is not callable

How to fix 

===================================================================================
For Lab 5 -- Exercise 2 -- Task 5 -- Step 3
az acr build --registry $acrName --image ipcheck:latest .

if you get error: 'NameType' object is not callable

First run command in Cloudshell: pip install azure-cli
Then restart CLI

There is  a problem with azure-cli on the default cloud shell v2.26.0.
it fixed on v2.26.1

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
