### ISSUE TITLE
Lab 8, Exercise 2

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#273]
# Module: 08
#### Steps: All

Description of issue

The lab steps should match the order *and* naming of the current UI.

Step 6 should be re-ordered. 

It should be:

Resource Group
Region
Resource name
Organization name
Administrator email

Step 6, viii should say 'Select Review + create' and then select 'Create'

Also, and this goes for most of the labs, it should say 'Wait for the deployment to complete before you move forward with this lab'.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
