### ISSUE TITLE
Lab 2 - Exercise 2 - Task 3 - Step 2

### ISSUE THREAD

**Issue by rkemish** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#276]
# Module: 00
#### Step: 00

Description of issue
The directory is no longer empty because of a previous exercise, it also repeats in the following exercise 3

Enter the following command, and then select Enter to change the current directory to the Allfiles (F):\Allfiles\Labs\02\Starter\func empty directory:

Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
