### ISSUE TITLE
Lab 11 Exercise 2 Task 2 Step 6 Issue with ConfigureService method in Startup class

### ISSUE THREAD

**Issue by ayanpatranabis88** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#279]
# Module: 11
#### Step: 6

**Description of issue**

_When I build the code, I am getting below error :-_

Startup.cs(34,18): error CS1061: 'IServiceCollection' does not contain a definition for 'AddControllers' and no accessible extension method 'AddControllers' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [C:\Ayan\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\Allfiles\Labs\11\Starter\Api\SimpleApi.csproj]
Startup.cs(35,18): error CS1061: 'IServiceCollection' does not contain a definition for 'AddApplicationInsightsTelemetry' and no accessible extension method 'AddApplicationInsightsTelemetry'
accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [C:\Ayan\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\Allfiles\Labs\11\Starter\Api\SimpleApi.csproj]

Repro steps:

1. A user was recommending import and usage of  Microsoft.AspNetCore.Mvc.NewtonsoftJson --version 5.0.9 but it did not help

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
