### ISSUE TITLE
lab_01 create web app GUI drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#284]
# Module: 01
#### Step: 16

Description of issue
Select **Next: Deployment (Preview)**
SHOULD BE
Select **Next: Deployment**
![image](https://user-images.githubusercontent.com/24426530/132116812-9b807a24-fa71-46ff-9975-9854304d5a4a.png)

#### Step: 3
 From the **ManagedPlatform** blade, select the **imgapi*[yourname]*** web app that you created earlier in this lab.
SHOULD BE
 From the **ManagedPlatform** blade, select the **imgapi*[yourname]*** app service  that you created earlier in this lab.
![image](https://user-images.githubusercontent.com/24426530/132117248-d46cd23f-1374-41b8-ad59-368ee2ba9e45.png)

Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
