### ISSUE TITLE
Lab 7 Error calling sync triggers (Bad Request)

### ISSUE THREAD

**Issue by luisdanielse** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#290]
# Module: 07
#### Step: 06

When I try to deploy the function app I receive the following error:

Error calling sync triggers (BadRequest)

I noticed that if I create the function app with Windows (instead linux in Task 4, step 8) it worked.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
