### ISSUE TITLE
Lab 06 Unable to create AD User on LOD

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#307]
# Module: 06
#### Step: 00

Description of issue
Students on LearnOnDemand cannot create AD Users (exercise 1 and 3) and are not allowed to create a new tenant (exercise 3).

Repro steps:

Run the following commands to create Azure AD users that you'll use to test Azure AD authentication:$passwordProfile = New-Object -TypeName Microsoft.Open.AzureAD.Model.PasswordProfile
$passwordProfile.Password = 'Pa55w.rd1234'
$passwordProfile.ForceChangePasswordNextLogin = $false
New-AzureADUser -AccountEnabled $true -DisplayName 'aad_lab_user2' -PasswordProfile $pas....

fails

1.
1.

**Comment by berkenbrack** [comment]
Thank you all for raising this to our attention.  Our support team is investigating this issue and working to address.  For any issues encountered with our azure pass alternative, please feel free to reach out to our support team directly: https://skillable.com/customer-support/ and is 24/7.

**Comment by molenaar** [comment]
Lab works like a charm this week on Skillable. Thanks @berkenbrack !

**Comment by molenaar** [comment]
@berkenbrack, I think we also need an Azure Pass alternative for the AZ-500 course too! I'll raise an issue there too.
