### ISSUE TITLE
Lab 04 Confusing steps, labs will not build

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#308]
# Module: 04
#### Step: 08-11

Description of issue
Its confusing for students to switch in the middle of a step from web to the context directory. 

Better 
Exercise 3 task 1: Adventureworks.Web
Exercise 3 task 2: Adventureworks.Context

Problem
Students forget to switch and the lab fails
AdventureWorks.Context doesn't compile in step 10, because the AdventureWorksCosmosContext class doesn't exist. It is created in the next step

Advise
Move steps 8 - 11 from Exercise 3: task 1 to task 2
First create the class and then modify code and try to build.

Another tip: the original source files contain references to the previous cosmosdb package (3.4.1). 
When a student forgets to add/update the package to 3.20, the code will not compile..

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review pull request solved for this Issue.

**Comment by JeffKoMS** [comment]
Closing issue.
