### ISSUE TITLE
Lab 05: Design doesn't match the lab instructions

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#309]
# Module: 05
#### Step: 00

Description of issue
It seems from the graphics that you create VM and on the VM you create an image with docker, push it  the registry and so on and so on...
However, you open the Cloud Shell and use the Registry to build an image.

Is this an upcoming change?

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
@molenaar I'll review this early next week and see if we can come up with a better graphic.

**Comment by JeffKoMS** [comment]
Lab 05 image has been updated.
