### ISSUE TITLE
Lab 9 Event Grip Topic new Networking tab

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#311]
# Module: 09
#### Step: 00

Description of issue
New tab **Networking** added in the Event Grid Topic wizard.

Repro steps:

Task 4: Create a custom Event Grid topic
1. On the Azure portal's navigation pane, select Create a resource.
2. On the Create a resource blade, in the Search services and marketplace text box, enter Event Grid Topic, and then select Enter.
3. On the Marketplace search results blade, select the Event Grid Topic result, and then select Create.
4. On the Create Topic blade, on the Basics tab, perform the following actions, and then select **Next: Networking**

5. ,,,,,   Next: Advanced:

**Comment by JeffKoMS** [comment]
The image includes the Networking tab, but we're not asking students to perform any actions on this tab so I'm not sure why we'd need to direct students to go through tab-by-tab versus just directly accessing the one they need to perform actions in.
