### ISSUE TITLE
Wrong step in service bus lab (Lab 10)

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#314]
# Module: 10
##### Step: 13

Description of issue
Step 13 - "static ServiceBusClient client;" is a duplicate of step 12
It should say "static ServiceBusSender sender;" instead as shown in the complete code in step 15

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review pull request solved for this Issue.

**Comment by JeffKoMS** [comment]
Closing since issue is resolved.
