### ISSUE TITLE
Lab 05: Unable to manually deploy a container image to Container Instances

### ISSUE THREAD

**Issue by kumud-sharma** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#316]
# Module: 05
#### Step: 05

Description of issue
I am trying to deploy a container image to Container Instances. but I am facing this issue. could you please suggest on that.
![image](https://user-images.githubusercontent.com/33771500/138481656-8c0c8f63-e977-4922-a88c-23a50ba38fa9.png)

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
This seems to be a transient error that happened during one week, please open a new issue if this problem continues.
