### ISSUE TITLE
Exercise 2 task 05 fails when trying to upload container to ACR

### ISSUE THREAD

**Issue by robertohern83** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#317]
# Module: 05
#### Step: 03

Description of issue

Executing exercise 2 on task 05 following the exact instructions in my machine, I had the following en step #3:

 Determining projects to restore...
  Restored /app/ipcheck.csproj (in 168 ms).
/usr/share/dotnet/sdk/3.1.414/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/app/ipcheck.csproj]
The command '/bin/sh -c dotnet publish --configuration Release --output out' returned a non-zero code: 1
2021/10/25 21:51:22 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Updating the project references to dotnet 5.0 fixed for me but I think that in previous steps you could specify the dotnet version required to create the project to avoid this issue...

Repro steps:

1. Follow all instructions up to the indicated step.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
This seems to be a transient error that happened during one week, please open a new issue if this problem continues.
