### ISSUE TITLE
Diagram in Lab 05 does not show what happens in the lab

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#318]
# Module: 05
#### Step: 00

Description of issue
The architecture diagram shows using the VM as a jump box to push an image to the ACR  and then pulling it from another location to push into container instance - in reality we are using the cloud shell to create the vm with ARM templates and also using cloud shell to build and push an image using ACR build tasks - so the diagram is not accurate although it is an appropriate way to do things. 
Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
Dup of #309 - will look to replace week of Jan 10.
