### ISSUE TITLE
lab 11 copy text includes part of markdown code block

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#319]
# Module: 11
## Lab/Demo: 11
Execrsise 02
#### Step: 05

Description of issue
The copy text includes csharp
Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
@AndrewConniff Can you let me know in which environment you're seeing the issue appear? I'm not seeing it on the [web](https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_11.html#exercise-2-monitor-a-local-web-api-by-using-application-insights) page and there are multiple instances of spaces after the language tag in a code block.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review pull request solved for this Issue.

**Comment by JeffKoMS** [comment]
Closing since it's resolved.
