### ISSUE TITLE
LAB 2, exercise-3 Task -3

### ISSUE THREAD

**Issue by manishrps** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#321]
# Module: 02
##### Step: 05

Description of issue: 
 
I didn't received the open command prompt after running the previous command (func start --build).

Note : it's very urgent, please revert me back as soon as possible.

@WaypointLizM  @AnuSridhar-25 @seesharprun

**Comment by manishrps** [comment]
Please reply it's very important.

@MrPeanutButta @renefc3 @MirkoFl

**Comment by seesharprun** [comment]
Thanks for reaching out. I'm a community contributor and don't actively work on this repository. I'm sure the owner of this repo is closing issues and PRs as fast as possible.

**Comment by molenaar** [comment]
Of course the command prompt will not appear because the Azure function is served locally. That's why you have to open another terminal.

On the taskbar, select the Windows Terminal icon again to open a **new instance** of the Windows Terminal application

**Comment by manishrps** [comment]
( STEP-5 ) When you receive the open command prompt, run the following command to start the httprepl tool, setting the base Uniform Resource Identifier (URI) to http://localhost:7071:

After opening new open command prompt, we are not able to run httprepl http://localhost:7071 these command, it's showing an error.

@molenaar

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
@manishrps We can't seem to repro the issue you're encountering. Please open a new issue if you're still having problems. We may need to get some more info from you.
