### ISSUE TITLE
10th dec major change

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#322]
# Module: all
#### Step: 00

Major update

Could anyone here send me a message what the major update will entail on the 10th December please.
I have a delivery up to the 10th and then another in January. Just need to understand the major changes, slides, labs or both.

I have looed on the MCT site and not aware of the detailed changes other than a major change is coming.

Repro steps:

1.
1.
1.

**Comment by molenaar** [comment]
In the week of the 10th, just deliver the current version and branch. If the update is too major you can always use older labs if you are not prepared yet. Major updates are not that major in general. Most is the same. Dont worry. Perhaps logic apps return. That would be the only new thing. Also expect changes in cosmos DB, more on api's. 

I have have been teaching Azure dev from 20532 until now. The most major change was the shift to dot net core.

**Comment by VitalyMCT** [comment]
@JeffKoMS I have the same questions: what's the nature of this December 10th "major update"? I don't see any changes to the labs beyond a couple of minor bug-fixes. Was the update delayed? Or was it not intended to involve labs in the 1st place?
