### ISSUE TITLE
Error calling sync triggers (Bad request)

### ISSUE THREAD

**Issue by AlanJ97** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#327]
# Module: 00
#### Step: 6
Description of issue
When I try to deploy my function I get next error:

![1](https://user-images.githubusercontent.com/51300800/142033625-9663503d-639b-486f-9455-dac6be17e75e.PNG)

and if we go to our azure portal I find this

![2](https://user-images.githubusercontent.com/51300800/142033687-c37df1c7-bb82-41a0-a618-5ca39924b06d.PNG)

The way in which I found I can solve it is just recreating the function, but why does this happen? Any ideas?

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.
