### ISSUE TITLE
Lab 7 local.settings.json updated

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#328]
# Module: 07
#### Step: 00

Description of issue
After creating a HTTP trigger, the local.settings.json file contains a propertie: IsEncrypted.

"Values": {
    **"IsEncrypted": false,**
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
}

The code snippets in step 5 and 6 should be updated.

Repro steps:

1.
1.
1.

**Comment by molenaar** [comment]
Also when you create
func new --template "HTTP trigger" --name "FileParser"

It asks for the language. You have to select C# and continue

**Comment by molenaar** [comment]
Mmm... it seems the local.settings.local looks totally different with the current 3.x version of Function Core Tools. I have to look into that...

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by JeffKoMS** [comment]
@molenaar Let us know in a new issue if you still believe any of the code needs to be updated.
