### ISSUE TITLE
Lab 4: An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by luisdanielse** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#331]
# Module: 04
#### Step: 06

Description of issue
When you try to see the details of a product you get the following error:
An unhandled exception occurred while processing the request.

![errorlab4](https://user-images.githubusercontent.com/18663693/143019570-4a0fa74d-e7a1-4220-9f2b-501caccffe83.png)

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment]
Closing since we can not duplicate.
