### ISSUE TITLE
Lab 05: Error when storing vm's public IP on variable using Azure CLI

### ISSUE THREAD

**Issue by GuilhermeSalkovski** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#332]
# Module: 05
#### Step: 08

Description of issue
Command line presented in the documentation generates an error when executed on Azure CLI:

**Command:** ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)

**Error:** ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv): The term 'ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
Documentation Source: <https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_05.html>

The correct command to store the public IP value on a variable would be:
**$ipAddress=az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv**

Repro steps:

1. Follow the instructions of Lab 05 (VM provisioning using Azure CLI) available on <https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_05.html> up to task  04, step 08.
2. Execute the command _ipAddress=$(az vm list-ip-addresses --resource-group ContainerCompute --name quickvm --query '[].{ip:virtualMachine.network.publicIpAddresses[0].ipAddress}' --output tsv)_ on Azure CLI

**Comment by tiagocostapt** [comment]
Are you executing the cmd on the PowerShell window of Cloud Shell? If so, try to change to Bash.

**Comment by GuilhermeSalkovski** [comment]
You are absolutely right.
I passed over the info about changing to bash and tried only on powershell.
Thank you!
