### ISSUE TITLE
Lab 05: Error when storing container registry name on variable using Azure CLI

### ISSUE THREAD

**Issue by GuilhermeSalkovski** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#333]
# Module: 05
#### Step: 04

Description of issue
Command line presented in the documentation generates an error when executed on Azure CLI:

**Command:** acrName=$(az acr list --query "max_by([], &creationDate).name" --output tsv)

**Error:** acrName=$(az acr list --query "max_by([], &creationDate).name" --output tsv): The term 'acrName=$(az acr list --query "max_by([], &creationDate).name" --output tsv)' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Documentation Source:** <https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_05.html>

The correct command to store the public IP value on a variable would be:
**$acrName=az acr list --query "max_by([], &creationDate).name" --output tsv**

Repro steps:

1. Follow the instructions of Lab 05, exercise 02, available on https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_05.html up to task 04, step 04.
2 . Execute the command  _acrName=$(az acr list --query "max_by([], &creationDate).name" --output tsv)_ on Azure CLI

**Comment by tiagocostapt** [comment]
Are you executing the cmd on the PowerShell window of Cloud Shell? If so, try to change to Bash.

**Comment by GuilhermeSalkovski** [comment]
You are absolutely right.
I passed over the info about changing to bash and tried only on powershell.
Thank you (again)!
