### ISSUE TITLE
Lab 6 - dotnet new command needs to be updated

### ISSUE THREAD

**Issue by varunrai** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#334]
# Module: AZ-204
#### Step: 03

With the availability of .NET 6 - the following command produces the boilerplate code without Program.cs and Startup.cs

Most of the lab is around .Net Core 3.1 and there is also a reference to Startup.cs 

It would be ideal to update the command and add the --framework parameter that would generate the code that is targetted for v3.1

```powershell
dotnet new mvc --framework .netcoreapp3.1 --auth SingleOrg --client-id <application_ID> --tenant-id <tenant_ID> --domain <domain_Name>
```

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by varunrai** [comment]
Depends on what .net core versions are installed in the lab environment.
In actual scenarios, the users might have more than one version installed in that instance dotnet new command would use the latest version. The latest dotnet version would not generate Startup.cs file.

**Comment by EdwinVanRooij** [comment]
I ran into this issue. I only had .net 6 installed on my machine, so I had to improvise a bit during the exercise.
This usually isn't really bad or hard, but it's not what you'd like to be doing while learning Azure.

**Comment by JeffKoMS** [comment]
The lab VMs only have .Net core 3.1 installed on them. We can look at adding --framework targeting, but honestly, I'd rather not encourage people to run these outside of our provided lab environments. Would rather have a single target to focus on for troubleshooting.

**Comment by EdwinVanRooij** [comment]
Then wouldn't the ideal solution be to update the lab environments to the latest LTS version? I do realize this may take a while to update all of the exercises, but I'm gonna assume we don't want to have only support 3.1 forever.

I'd be willing to take some of the work upon myself, I'm still learning Azure myself, so some more repetition definitely won't hurt :).

**Comment by varunrai** [comment]
@EdwinVanRooij Yes, the same thing happened to me but since I knew the root cause it took me little time to fix it but I know there were a few people who struggled with it especially if they have little to no experience in .Net Core.

I do agree. The labs and the VM's should be updated to support the LTS version.

**Comment by JeffKoMS** [comment]
Yep, it's 2022. And, no, it's not that simple. Here's a couple of the reasons why:

- Changes to VMs need to go through a ton of governance and compliance checks and that takes time.
- The content of the AZ-204 course itself would need to be updated to .NET 6 as well. If the exercises and coding examples in the course aren't in sync with the labs there will be many more questions from students about the differences. **The course update to .NET 6 is on the to-do list, but that won't be live until mid-calendar year at the earliest.**
- There are more reasons, but this reply is already long enough.

If a lab hosting provider is giving students a lab environment that isn't following the build guidelines then I encourage all of you to ask your students to file a bug against the lab hosting provider. We don't control what they do, we can only give them the build guides.

If you have students that insist on doing the labs on their own machines then they should be prepared to make some changes. If that presents a big hurdle for the student then I would encourage you to direct them to the environments/subscriptions provided in the course.

**Comment by thavetta** [comment]
I know that this change is not easy, but LTS time is only 36 months. Today, 3 months, 8 % from .NET 6 LTS, are past. .NET 6 did not appear suddenly. We live with .NET 6 more than 6 months. 3 months with preview, 3 months with final version. I changed all my C# courses to .NET 6 from .NET Framework 4.8 in two months. Alone.

**Comment by EdwinVanRooij** [comment]
@JeffKoMS ahh okay, I didn't realize the requirements and consequences of changing the exercise documentation. Glad to hear it's on the to do list.

Maybe a good immediate solution would be to add a general warning to these docs, something like: 'Please note that if you decide to perform this exercise locally instead of in a lab environment, the results of commands may differ.'

However, I would understand that it can be assumed that this is the case, therefore the warning wouldn't add much value.

**Comment by WigF1** [comment]
Just to echo @JeffKoMS's comment. The course is specifically designed to be delivered using ALH only. It says that in the MOC title plan; all MCTs and Partners should know and be aware of this. 

Some ALH have Windows 11 installs, nothing pinned to the taskbar / start menu etc. This is unsupported. If your ALH is using this, then they need to be notified that *they* are the ones causing your students issues, not MSL, the contributors of this repo, nor the courseware content creators.

**Comment by JeffKoMS** [comment]
Updating the labs to .NET 6 is underway and all commands in the new labs will specify the correct framework so there's no confusion as to why something isn't working on someone's personal machine. Updates should be available by end of June.

**Comment by ParamRamki** [comment]
Today I've encountered the same issue.
