### ISSUE TITLE
module 2, lab 2 exercise 1 task 2 issue - resource group

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#335]
# Module: 02
#### Step: 02

Description of issue
Creating the storage account it states you need to create a new resource group. It should say select the existing resource group
Repro steps:

Task 2: Create an Azure Storage account
In the Azure portal, use the Search resources, services, and docs text box to search for Storage Accounts, and then, in the list of results, select Storage Accounts.
On the Storage accounts blade, select + Create.
On the Create a storage account blade, on the Basics tab, perform the following actions, and then select Review + create:
Subscription drop-down list	Retain the default value.
Resource group section	Select Create new, enter Serverless, and then select OK.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review found Module 2 worked as written

**Comment by clifford-smith** [comment]
![image](https://user-images.githubusercontent.com/78555251/152632869-0917b778-623f-435c-9278-565ac1752e6f.png)

The Serverless resource group is created in this step. So it wouldn't be listed as an existing resource group. Could you clarify your issue?  As the instructions already match the repro steps you listed.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment]
Closing this issue since we can't repro.
