### ISSUE TITLE
missing starter files in lab 6

### ISSUE THREAD

**Issue by insert314Here** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#336]
# Module: 06
#### Step: 00

Description of issue: I do not see the starter files for lab 6

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review found Module 6 worked as written

**Comment by JeffKoMS** [comment]
The students create their own starter files for this lab by using the following command: 

`dotnet new mvc --auth SingleOrg --client-id <application_ID> --tenant-id <tenant_ID> --domain <domain_Name>
rmdir .\obj /S /Q`

I added the starter folder structure in the AllFiles so students can follow the steps without having to create the folders themselves.
