### ISSUE TITLE
error in lab 3 answer key (wrong method)

### ISSUE THREAD

**Issue by ececiu** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#35]
Exercise 4, task 2: 
In the EnumerateContainersAsync method, enter the following code to get a new instance of the BlobContainerClient class by using the GetBlobContainerClient method of the BlobServiceClient class, passing in the containerName parameter:

should be replaced with:
In the EnumerateBlobsAsync method,

**Comment by seesharprun** [comment]
Which step number are you seeing this error?

You can respond in the following format:
- **Exercise**: 4
- **Task**: 2
- **Step**: ?

I looked in the answer key document and could not find this issue.

**Comment by ececiu** [comment]
- Exercise: 4
- Task: 2
- Step: 2

**Comment by seesharprun** [comment]
I'm not seeing an issue with Exercise 4, Task 2. The instructions don't seem to match up with your description.

Did you mean Exercise 4, Task 1, Step 2?

Task 1 is focused on implementing the ``EnumerateBlobsAsync`` method.

Task 2 is focused on implementing the ``GetContainerAsync`` method.

**Comment by ececiu** [comment]
yeap, sorry, probably I'm too tired for today :)
exercise 4, task 1, step 2

**Comment by seesharprun** [comment]
No problem, I fixed it in 419907fff56015c6149df9aec19301c94d7a4a26
