### ISSUE TITLE
Lab6: Command for removing directory leads to an error

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#350]
# Module: 6
#### Step: step 3

Description of issue
The command `rmdir .\obj /S /Q` returns following error
`Remove-Item : A positional parameter cannot be found that accepts argument '/S'.`

Fix:

 using a native PS command e.g. `Remove-Item -Path .\obj -Force -Recurse`
OR
removing the folder manually in explorer.

**Comment by unaihuete93** [comment]
Or running command line instead of Powershell 

![image](https://user-images.githubusercontent.com/64772417/146532601-ca5a5a3b-a1e1-493e-813e-a10d038ec092.png)
make sure they use cmd, not PS

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review found Module 6 worked as written

**Comment by bechynsky** [comment]
Instructions are confusing. See screenshot.

<img width="551" alt="az204l06e02t01" src="https://user-images.githubusercontent.com/4288542/158993660-a605ce12-c2e5-4c24-95c0-fef6a85b85f4.png">

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment]
Changing the directions so it instructs students to open the Windows Terminal to help avoid confusion.
