### ISSUE TITLE
Azure event grid - Knowledge check

### ISSUE THREAD

**Issue by RashmiSrinivas1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#355]
# Module: 09
#### Step:  

Description of issue

Go to knowledge-check in module 9. Question 2: 
https://docs.microsoft.com/en-us/learn/modules/azure-event-grid/9-knowledge-check

Expected: 
The answer should be incorrect for` Event Grid Subscription contributor`
![image](https://user-images.githubusercontent.com/50584240/147423132-d260260c-efc0-446e-bb81-e52351e8962e.png)

**Comment by JeffKoMS** [comment]
Thanks, the change should go live to Learn shortly. In the future please use this GitHub only for Lab issues. You can use the feedback option on the page on Learn and it will generate a bug.
