### ISSUE TITLE
Terminology used in instructions?

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#357]
# Module: All

Description of issue

Why are we using the term "Azure portal's navigation pane" instead of "Portal menu" ? 
Why are we using the term "Search resources, services, and docs text box" instead of "Global search" ?

The items are listed here: https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-overview details 

It just seems odd that we are inventing terms to use that do nothing other than (a) make instructions way more verbose than they need to be and (b) confuse students.

I'm more than happy to change all instances of the terms to be the correct ones.

**Comment by JeffKoMS** [comment]
They're also commonly referred to as panes ("left pane", "working pane", etc.). We could change the references to "menus" - are students getting confused by our naming?

For the "Search resources, services..." question those are the words in the global search box. At times when there's multiple ways of searching/filtering on Azure present on the same screen this ensures students know which one to use. Also, for accessibility not sure "Global search" would be all that helpful.

**Comment by JeffKoMS** [comment]
I'm going to include this work (aligning to the new terms where we can) in our efforts to update the labs to .NET 6, which I'm hopefully going to get completed by the end of June (possibly a bit sooner). Will close this for now.
