### ISSUE TITLE
Lab 4 Title

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#358]
# Module: 04
## Lab/Demo: 04

Description of issue

Now that there is no SQL bacpac, no importing, no migration etc. is the title "Construct a polyglot data solution" still valid? Would it not be better to call it "Using Cosmos DB in a web app" or something similar?

**Comment by msftnutta** [comment]
Hi @JeffKoMS This could be easily done, however, I do not have the control over AZ-204 lab index page, so I won't be able to create a pull request and have this issue fixed.
