### ISSUE TITLE
LAB 11 "dotnet dev-certs https --trust" needed before running website

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#361]
# Module: 11
#### Step: 00

Description of issue
![image](https://user-images.githubusercontent.com/64772417/149499611-8a3ea364-776c-4fc0-8e73-d28cf9b6c45e.png)

Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
@unaihuete93 Can you let me know which lab hosting provider you are using when this error occurs?

**Comment by unaihuete93** [comment]
@JeffKoMS this was an screenshot taken by a students using LODS (tested it with LODS myself too)

**Comment by JeffKoMS** [comment]
Update was just made to the lab steps (based on your PR).
