### ISSUE TITLE
Lab 7 - Azure Key Vault: Migrate from proprietary Access Policies to RBAC

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#363]
I think the lab should be updated to reflect the current best-practices around AKV security.

Please refer to https://samcogan.com/its-time-to-move-to-rbac-for-key-vault for details.

**Comment by JeffKoMS** [comment]
@VitalyMCT Sounds like a good idea, we'll keep this in mind for the next round of lab updates which I'll try to schedule for mid-calendar year.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review found Lab 07 worked as written

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review It's a design recommendation, to make the lab consistent with Microsoft's best-practices for AKVs.  

There was not a claim that the lab does not work as written.
