### ISSUE TITLE
Upgrade labs from .NET Core 3.1 to .NET 6

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#364]
I realize there are still a few months of official support remaining for .NET Core 3.1. 

However, it would be ideal to show students current technology instead of a legacy one. 

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by ChRocheFR** [comment]
I agree at 100%.
Lab provider are moving to Windows 11 with .NET 6 installed as one and only .NET framework. 

Clearly labs need to be updated

**Comment by JeffKoMS** [comment]
Agreed, will also make code easier to present and use. Definitely on the plan to execute. Probably won't happen until mid calendar year.

**Comment by VitalyMCT** [comment]
@JeffKoMS Can we please keep outstanding items open on GitHub? 

Otherwise I find they often risk getting misplaced in the system, then we have to open redundant new issues, etc.
