### ISSUE TITLE
Lab 09 step 19 &lt; in the instruction code = should be <

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#371]
# Module: N/A
#### Step: 19

Description of issue
Lab 09 step 19 &lt; in the instruction code = should be <
Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
@AndrewConniff I've looked through the markdown in Lab 09 and there is no instance of "&lt;" in the markdown. What environment are you seeing this happening?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by JeffKoMS** [comment]
I've scrubbed all of the labs and removed blank lines as mentioned in #351. The PR #466 will be merged this Friday. Closing this.
