### ISSUE TITLE
ALL LABS remove punctuation from TABLES and lists

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#373]
# Module: 00
#### Step: 00

Description of issue
MULTIPLE USERS - follow instructions and input values with the punctuation which breaks CONTAINER images week in and week out.
also punctuation in lists and tables is incorrect form for lab content.

Repro steps:

1.
1.
1.

**Comment by JeffKoMS** [comment]
@AndrewConniff Can I assume this is in reference to Lab 05? Or, is this about all of the lab content in general? Can you give me a specific example of what you're referring to? I've looked through a good number of the labs and I'm not sure I'm seeing the issue you're pointing out.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by JeffKoMS** [comment]
@AndrewConniff PR's have been merged, let us know if you see this issue in any other labs.
