### ISSUE TITLE
Lab VM software update

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#374]
Can the VM images for ALHs please be updated with the current software versions?

Examples:

Windows Update patches
VS Code
New Edge
Azure Storage Explorer
etc.

Rationale: current versions are out of support, officially or practically. Staying current would help with supportability and with demonstrating Azure development best practices. 

Example for Azure Storage Explorer - message appears when opening the app on the lab VM:

![image](https://user-images.githubusercontent.com/1765732/151667461-9c074341-80a2-45ad-8c3c-934917136fdb.png)

**Comment by JeffKoMS** [comment]
@VitalyMCT Thanks for letting us know, we'll start investigating getting an update in place.
