### ISSUE TITLE
Lab 2 - Missing Link

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#381]
Search for "[start the function app project locally]" in Markdown. There are 3 or 4 references.

It seems the intent for these was to have a link, however, the URL is missing.

**Comment by JeffKoMS** [comment]
@VitalyMCT Seems like it was an attempt to point students to the  [docs](https://docs.microsoft.com/azure/azure-functions/functions-develop-local) page for more information. Not sure that has a lot of value for students in the middle of the lab. I'll update the link for now, can delete later if it proves to distract students too much.
