### ISSUE TITLE
Lab 11 - HTTPS certificate Issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#389]
Reopening #282. Please review the fix for that issue - it seems to have been closed without merging.

Edit: This is the PR that needs to be merged: https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/pull/283

**Comment by JeffKoMS** [comment]
A fix for this has been implemented.
