### ISSUE TITLE
Lab 03 code samples are incorrect Multiple errors

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#393]
# Module: 00
#### Step: 10

Description of issue
Observe the Program.cs file, which should now include:  This code does not work and has blobClient.Uri in an out of scope call and the solution code does not have that code. 
repro steps:
Go through the lab and verify all the code matches up. 
1.
1.
1.

**Comment by mkennten** [comment]
Running into this, too. Looks like some extra added lines at the wrong places.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by msftnutta** [comment]
agreed with @MOC-Labs-Review , move this to the closed issue.
