### ISSUE TITLE
Lab 6

### ISSUE THREAD

**Issue by ggumbiner** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#439]
# Module: 6
#### Step: 00

The lab does not seem to match what is being discussed in module 6. The title of the lab is "...Authenticate by using OpenID Connect, MSAL, and .NET SDKs..." yet there is no exercise for MSAL etc.

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by msftnutta** [comment]
@ggumbiner Can you please tell us more about this lab?

**Comment by ggumbiner** [comment]
Thank you for reaching out to me concerning this lab in AZ-204.

As best as I can explain it, the ppt slide for lab objectives (which I have included as images following in this email) discusses using the Microsoft Identity Platform, including libraries such as MSAL and Microsoft Graph SDK. 
On github the lab 6 instructions are entitled: 
  Lab 06: Authenticate by using OpenID Connect, MSAL, and .NET SDKs
  The lab instructions, on github (https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_lab_06.md) has students doing the following exercises:
     1) Exercise 1: Configure a single-tenant Azure AD environment     2) Exercise 2: Create a single-tenant ASP.NET Core web app     3) Exercise 3: Configure a multitenant Azure AD environment     4) Exercise 4: Configure a multitenant ASP.NET Core web app
It is my observation, that the lab exercises as set forth above do not have students doing any MSAL or Micrsoft Graph which was set forth in the lab instructions as lab objectives (See images that follow). 
A search of the lab instructions has no mention of MSAL or Micrsoft Graph. 
I could not find anything in the exercise instructions for this lab that have students doing anything with MSAL or Microsoft Graph.
This led to my conclusion that the lab objectives and the instructions do not match.
If you have any questions or want to discuss this issue further, please feel free to reach out to me.
Cheers.










   



 On Thursday, May 26, 2022, 11:06:08 PM CDT, msftnutta ***@***.***> wrote:  
 
 


@ggumbiner Can you please tell us more about this lab?

**Comment by unaihuete93** [comment]
Microsoft Identity Web is a set of ASP.NET Core libraries that simplifies adding authentication and authorization support to web apps and web APIs integrating with the Microsoft identity platform. It provides a single-surface API convenience layer that ties together ASP.NET Core, its authentication middleware, and the [Microsoft Authentication Library (MSAL) for .NET](https://github.com/azuread/microsoft-authentication-library-for-dotnet).

**Comment by unaihuete93** [comment]
these samples could also be used: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user

**Comment by msftnutta** [comment]
thanks for the clarification @ggumbiner we will move this to a work item to improve this lab.

Thank you @unaihuete93 for the suggestion.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.
