### ISSUE TITLE
Module 6, Lab 6, Exercise 3, Task 2 Step 3

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#441]
# Module: 06
## Lab:06
##Exercise 03
#### Step: 03

Description of issue
Users are using the skillable labs. They are also using Azure passes. has the labs been tested using azure passes?
The issue is simple, when the second tenant is created, its outside the subscription, so when you get to step 3, there is no subscription outside the tenant so unable to continue with the work. They all had this issue.

Thanks
Davide
Repro steps:

1.
1.
1
![issue1](https://user-images.githubusercontent.com/59872097/157486529-52feb2bf-b98b-43cb-b59e-53b77ef2e6f1.JPG)
.

**Comment by donaldcng** [comment]
Encounter the same issue.

**Comment by donaldcng** [comment]
It's too complicated and cannot process. Suggest using the Azure Portal to create a new user.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by msftnutta** [comment]
@JeffKoMS  since we're moving to CloudSlice, this issue will be no longer exist. Please close it.
