### ISSUE TITLE
Add multiple subscriptions instruction

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#444]
# Module: 01
#### Step: 10

It is common that attendee has more than one subscription. We should have instructions how to set active subscription.

Add steps after S10 or warning

- 	Run az account list
- 	If you see more subscriptions set active one to Azure Pass

```	
	# Certain keys are filtered out and not printed in the table view. These keys are id, type, and etag. To see these values, you can change the key name in a multiselect hash.
	# https://docs.microsoft.com/en-us/cli/azure/query-azure-cli
	
az account list --query "[].{name:name, SubscriptionId:id, state:state}" --output table --all
	az account list --query "[?starts_with(name, 'Azure Pass') && state=='Enabled'].{name:name, SubscriptionId:id, state:state}" --output table --all
	az account list --query "[?starts_with(name, 'Azure Pass') && state=='Enabled'].{id:id}" --output tsv --all 
	
	az account set --subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 ```

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by msftnutta** [comment]
@JeffKoMS with CloudSlice, this issue won't exist anymore.

**Comment by msftnutta** [comment]
I've put the generic commands under the section 'Before you start' thanks for reporting this @bechynsky

**Comment by tiagocostapt** [comment]
Aren't the labs supposed to only support Azure Pass subscriptions and require a new Microsoft Account? 
This will add unnecessary steps for like 99% of the executions of this lab. I have to disagree with @bechynsky, most of my students create a specific account/subscription for the training. In some cases, we even have to do some Azure AD configurations, and using a corp account will not work due to a lack of authorization to do it. Example - Register an application. 

Most students will just take those steps and don't even read the previous message.
Any other plans why this is needed?

**Comment by msftnutta** [comment]
@tiagocostapt I think it's a good idea to have an overview on how to manage the multiple active subscriptions prior to the lab which I've just added.

It's the generic guidelines tho.

**Comment by tiagocostapt** [comment]
@msftnutta you're the one running the repo so my comment was just trying to give feedback from the field. I guarantee that this change in the labs will cause people to find it confusing and will start to question MCTs why they need to do it etc... Nowadays students have a hard time reading instructions. 

- If students are taking the labs using a lab hoster or using Learn sandboxes there's no need for this. They only have 1 sub.
- Most students that take the course and don't use a lab hoster only have a single subscription setup. Personal Microsoft account + Azure Pass.
- Only a minority will control an Azure AD + more than 1 sub as a demo environment to take the class. 

This is just my feedback from teaching Azure for some years.

**Comment by msftnutta** [comment]
@tiagocostapt right now the instructions are at the very top and clearly mention that if the users have multiple active subscriptions. they should be looking to ensure they choose the right subscription. 

![image](https://user-images.githubusercontent.com/98095529/170811119-1a716eb6-7e05-4583-8cb3-dfbdd1b9181b.png)

we have been receiving feedback to give learners the guideline on how to manage multiple active subscriptions, but if the learners have only one active subscription, they can simply skip this part.

Let's this new section stay for a little while and see whether this would cause more confusion to learners or turn out to be a benefit to learners. Then, we will decide from there :)
