### ISSUE TITLE
More clear instruction to run function

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#445]
# Module: 02
##### Step: 03

We need to add some warning that function must running and student need to open new Terminal. Unfortunately majority of students are not familiar with concepts of command line. Maybe screenshot with two terminal or something like that.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
