### ISSUE TITLE
Use curl instead of httprepl

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#446]
# Module: 02
##### Step: 05

Switch instructions to use curl. Curl is available in Terminal. Majority of students doesn't understand concepts of command line.

**Comment by WigF1** [comment]
If anything, the use of HTTPREPL would make it easier then? If a student doesn't understand the command-line, surely using familiar single-term commands like CD, GET etc would be easier rather than typing out an entire CURL expression?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by msftnutta** [comment]
agreed with @MOC-Labs-Review , move this to the closed issue.
