### ISSUE TITLE
Lab 03 - Missing Brackets 

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#449]
# Module: 03
#### Step: 09 & 10

Description of issue

Missing Brackets in Program.cs 
Immediatly behind `public static async Task Main(string[] args)`
and the closing Bracket for `EnumerateBlobsAsync`-Method

Repro steps:
- Observe the Code Listings

**Comment by AndrewConniff** [comment]
This is still broken and it also has the <> brackets as &lt; etc.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by adntobias** [comment]
![2022-04-12_08h08_02](https://user-images.githubusercontent.com/55876240/162893582-52d031c5-8590-4d27-9ad6-2af771d4fb87.png)
![2022-04-12_08h15_11](https://user-images.githubusercontent.com/55876240/162893585-997e0507-8b6b-4a89-b1ce-727b37ec37e1.png)

**Comment by JeffKoMS** [comment]
resolved in #467 and #468
