### ISSUE TITLE
Lab 5, Exercise 1, default size for the VM is not allowed for the Azure Pass.

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#450]
# Module: 5
## Lab: 5
Exercise: 1

Description of issue
The default size for the VM doesn't allow the creation for the Azure Pass

Fix:
Override the default size. Add `--size Standard_D2as_v5` to the command line specified in the lab

**Comment by msftnutta** [comment]
@JeffKoMS  please close this issue.
