### ISSUE TITLE
Lab 02 Exercise 3 task 5 step 3-6- no brackets in code results in build failure.

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#454]
# Module: 02
#### Step: 05

Description of issue
The code import shows the run command but does not include the opening and closing brackets so the build fails. For non-C# developers, the fix is not obvious.
Repro steps:

1.
1.
1.

**Comment by WigF1** [comment]
Are you sure you have the right Module / Lab / Exercise etc? There is no Task 4 or 5 for exercise 3?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment]
@AndrewConniff There's only one lab with exercise 3 task 5, and it's lab 7.  Not seeing anything there related to a code import or a run command that is missing brackets. Going to close, feel free to create a new issue if needed.
