### ISSUE TITLE
Lab 12, Exercise 02, Task 3 - instructions outdated

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#455]
# Module: 12
#### Step: 00

Description of issue

Since CDN and Front Door have been consolidated, the instructions no longer match. 

Steps should be:

1. On the Azure portal's navigation pane, select Create a resource.
2. On the Create a resource blade, in the Search services and marketplace text box, enter CDN, and then select Enter.
3. On the Marketplace search results blade, select the 'Front Door and CDN profiles' result, and then select Create.
4. On the Compare offerings page, select 'Explore other offerings' and then select 'Azure CDN Standard from Akamai', and then select Continue.

The existing steps can then remain, including the screenshot.

See #456

**Comment by unaihuete93** [comment]
correct ! 
![image](https://user-images.githubusercontent.com/64772417/161239535-a4533c44-d150-40b5-91d9-77a69dca14dd.png)

**Comment by AndrewConniff** [comment]
agreed - it is far simpler and less risky of change in GUI to have them go to the storage account and search the left side for CDN and select Azure CDN.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this pull request.

**Comment by JeffKoMS** [comment]
Merged PR #456
