### ISSUE TITLE
Lab 05 - variable value causes error

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#457]
# Module: 05
#### Step: 01

Description of issue

The instructions say to run the code to create a value for the registryName variable that is as follows:

![image](https://user-images.githubusercontent.com/12164329/161906467-ba6fa2c5-debd-4d77-b502-3400adf48643.png)

However, if that name isued the following error now appears:

![image](https://user-images.githubusercontent.com/12164329/161906384-4f723478-cc7e-449a-a236-ec3e2bdc4d2b.png)

The instructions should be modified to set the variable value to 

```
registryName=conregistry$RANDOM
```

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.
