### ISSUE TITLE
Module 6 / Lab 6 Ex2 Tsk 1 Step2 & 3

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#465]
# Module: 06
#### Step: 03

Description of issue
Step 2 and 3 need fixing
Step 2 asks to create a folder odbcclient. The download file now includes the folder structure, so the md command needs removing

Step3 command does not work, need to remove rmdir \obj /S /Q
Repro steps:
![issue4](https://user-images.githubusercontent.com/59872097/165517209-9f5fa7ba-6531-4f28-8711-f9e86c082bef.JPG)

1.
1.
1.

**Comment by msftnutta** [comment]
Thanks for rasing this issue, I've created a pull request #467 for a fix.

**Comment by WigF1** [comment]
@JeffKoMS 

This issue needs reopening - an incorrect change was made in that the instructions only contains the MD command not the CD command.

![image](https://user-images.githubusercontent.com/12164329/167786307-a63de475-3958-47a0-a2ca-2ecf905b0471.png)
