### ISSUE TITLE
Typo in the main instructions of the lab

### ISSUE THREAD

**Issue by Sirmyself** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#470]
# Module: 204
### Task: Sign in to the lab virtual machine

There is a typo in the instructions to log on the virtual machine. Instead of reading "click [ctrl+alt+del]", we see "lick".

 1. Open a lab
 2. Scroll down to "Sign in to the lab virtual machine"
 3. The typo is in the first step of the section.

**Comment by rob-foulkrod** [comment]
That may be lab provider specific. I don't see where the lab instructions contain those steps.

**Comment by Sirmyself** [comment]
could be, I can't find it in the git hub either, maybe it's on a shared instruction library or something. those instructions are the same through all labs of the module

**Comment by msftnutta** [comment]
I've raised the [issue ](https://github.com/LODSCloudSlice/AZ-204T00-A-Cloud-Slice/issues/1)to CloudSlide directly 

@JeffKoMS Please help to close this issue, Thanks @Sirmyself for reporting this.

**Comment by msftnutta** [comment]
move this to the closed issue, since we already reported to Skillable / CloudSlice directly.
