### ISSUE TITLE
Microsoft Azure Function App creation has changed; need to update lab instructions

### ISSUE THREAD

**Issue by JBrunskowski** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#487]
# Module: 02
#### Step: 05 & 06

Description of issue
In the lab, Step 6 mentions choosing the Operating System and Plan within the Hosting portion of the Function App creation. However, these need to move to Step 5 as the only option in the Hosting portion is now "Storage account".

**Comment by msftnutta** [comment]
Thanks, @JBrunskowski for opening this issue.

Exercise 1: Create Azure resources > Task 3: Create a function app > both steps 5 and 6 need to be cleaned up. @JeffKoMS 

Please use the following screenshot for Step 5

![image](https://user-images.githubusercontent.com/98095529/168828083-66b9748b-4fcd-44f0-a165-c95ffa2e0a2d.png)


and this following screenshot for Step 6

![image](https://user-images.githubusercontent.com/98095529/168828239-8c16cced-7504-4061-9299-9216ffbc1ed9.png)

**Comment by msftnutta** [comment]
@JBrunskowski we have created pull requests and get both instructions and screenshots updated. Thanks.
