### ISSUE TITLE
Lab Virutal Machine Setup - Error with Windows Terminal configuration

### ISSUE THREAD

**Issue by ricardo-bazan** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#489]
# Module: 00
Lab Virutal Machine Setup 

Description of issue
I copied and pasted the windows terminal configuration into mine, but it shows an error on loading users' preferences when starting the terminal.
Repro steps:

1. Copy Windows Terminal configuration
2. Paste on the terminal JSON settings
3. Run terminal and error will be shown

![imagen](https://user-images.githubusercontent.com/48494023/169184186-e1ebba86-79f0-4fe3-bded-212c77b97842.png)

**Comment by WigF1** [comment]
Labs are not designed to be run locally, only through an ALH.

**Comment by msftnutta** [comment]
Agreed wit @WigF1  

@JeffKoMS  Please close this issue.
