### ISSUE TITLE
Lab 11 Screenshot update

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#490]
![image](https://user-images.githubusercontent.com/64772417/169528165-8ec833c8-f621-4a82-83e7-5d7d78b17894.png)
update screenshot

**Comment by msftnutta** [comment]
Thanks @unaihuete93  for raising this issue, It's been fixed with a pull request #491 and have successfully merged into the main branch.
