### ISSUE TITLE
Code missing "PublicAccessType.Blob"

### ISSUE THREAD

**Issue by ylarinne** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#5]
# Module: 3
#### Step: 6

In step 3, everything is ok:

await container.CreateIfNotExistsAsync(PublicAccessType.Blob);

But in step 6 "Observe the GetContainerAsync method, which should now include:" 
the same line is

await container.CreateIfNotExistsAsync();

So it is missing the PublicAccessType.Blob

Students who copy the whole code from step 6 won't get the Task 5 working where this is tested, without setting the access level manually.

**Comment by seesharprun** [comment]
Great catch!
