### ISSUE TITLE
Run is failing while performing the task - Deploy a Docker container image to Container Registry

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#509]
# Module: 5
#### Step: 03

Description of issue 1: **Run Failed while following the instructional steps to upload the source code to your container registry and build the container image as a Container Registry task**

After executing the below command - 'Run failed' error is thrown. Tried to recreate the lab, again the same error is thrown. 
 **'az acr build --registry $acrName --image ipcheck:latest .'** 

Repro steps of Issue 1:
1. **Lab 5 >> Exercise 2 >>Task 5 >> Step 3**

![Lab5_error_runfailed](https://user-images.githubusercontent.com/92770552/172388500-cd540772-c16e-4b25-9df8-de019ffff0d9.png)

![Lab5_error_runfailed2](https://user-images.githubusercontent.com/92770552/172388577-8c54f0d5-4c9f-47c0-ba68-2ab71e58b8e0.png)

### Need more clarification on the instructional steps on performing the tasks in root directory :

Task 1 - We are executing the command to move from the root directory to 
**cd ~/clouddrive** and continuing the next three tasks (T2, T3 and T4) in the same **cd ~/clouddrive** directory.

In the Task 5 there is an instruction to change the directory to **cd ~/clouddrive/ipcheck** however there were no instructions either to close the cloud shell or to change the directory to root.

Steps from the lab E2>>T5>>S1
**Run the following command to change the active directory from ~/ to ~/clouddrive/ipcheck:
cd ~/clouddrive/ipcheck** 

Since the Task1 we are executing the command in the directory **cd ~/clouddrive/ipcheck** only hence the step #1 in Task5 is confusing. If we are going to perform the task in **cd ~/clouddrive/ipcheck** then we can include the note to make sure we are in the respective directory.

**Comment by msftnutta** [comment]
@ParamRamki I've tested it by using Azure Cloud Shell and found no issue, Could you please help to confirm whether this is still a problem on your side?

**Comment by JeffKoMS** [comment]
@ParamRamki Looking at the error message it looks like there are some .NET version conflicts. Are you running this in an environment with multiple versions of .NET installed?

**Comment by ParamRamki** [comment]
> @ParamRamki I've tested it by using Azure Cloud Shell and found no issue, Could you please help to confirm whether this is still a problem on your side?

Yes, I tried more than 3 times by clearing the resources and faced the same issue. I also deleted the ipcheck folder from the cloud storage before proceeding with the lab.

**Comment by msftnutta** [comment]
@ParamRamki  if you run this on Azure Cloud Shell, it should be work. May I know if you run this locally by using PowerShell on Windows? 

Can you hep to run this 2 commands and let us know your output?

`dotnet --version`

`az version`

**Comment by ParamRamki** [comment]
I executed the command in Azure cloud shell and this the output


![image](https://user-images.githubusercontent.com/92770552/172431080-2b95ad7d-b5d2-465f-9ac3-57a88d143026.png)

This is the regedit details in the local machine
<img width="526" alt="image" src="https://user-images.githubusercontent.com/92770552/172430871-9c9818a3-84f9-4ce1-8982-b0be29b971d8.png">

**Comment by JeffKoMS** [comment]
@msftnutta This issue is Lab 5, the PR you just merged was for Lab 3.

**Comment by ParamRamki** [comment]
Yes I'm using the Skillable Lab environment. Thanks!

**Comment by msftnutta** [comment]
@ParamRamki can you capture the bigger screenshot starting from the command you executed, console + output error you see.

**Comment by ParamRamki** [comment]
Thanks I'm encountering the following error in lab 6 while accessing cloud shell >> powershell, will open an new issue.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/92770552/172455272-c236da5e-813d-4fe2-9c83-7732894ed3d9.png">

**Comment by ParamRamki** [comment]
Is this issue related to the closed ticket - Update .Net SDK to 6.0 #503
