### ISSUE TITLE
Lab 06 command not working

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#515]
# Module: 06
#### Step: 05

Description of issue
![image](https://user-images.githubusercontent.com/64772417/172617276-5fd10771-ae2d-4f5e-b279-4442734695b0.png)
![image](https://user-images.githubusercontent.com/64772417/172617629-2c67fbba-0586-4094-b63a-6636227c0ecb.png)

Task should be modified to something like --> **(Get-AzureADUser -Filter "DisplayName eq 'aad_lab_user-23942396'").UserPrincipalName**

**Comment by unaihuete93** [comment]
CloudSlice/LODS should also be notified as the replace the full  UPN in the task, it should be only display name
GITHUB
![image](https://user-images.githubusercontent.com/64772417/172618253-834f6ff5-7f27-4f38-8eee-2cf8aef79b74.png)

LODS
![image](https://user-images.githubusercontent.com/64772417/172618434-41957363-aec6-40f0-8a9e-927ca6e0a929.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue

**Comment by unaihuete93** [comment]
it is an issue related to LODS/Cloudslice, but were told to report any labs issues in these repositories.

**Comment by msftnutta** [comment]
@JeffKoMS @unaihuete93 I've put the screenshots explains on how to check the UPN easily in the portal. This issue definitely occurs only when we use CloudSlice. So with the screenshots, hope it helps.
