### ISSUE TITLE
Intructions are outdated for CloudSlice environment

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#531]
The instructions that people see in the lab environment with CloudSlice. These must be updated. It's very confusing to the learners and adds a huge load to the trainers, and heavily affects the learning experience.

To my knowledge, these instruction in our Repo or separate from the Lab environment. I'm opening this ticket to raise awareness of the issue.

Thanks

**Comment by msftnutta** [comment]
@houbena  please specify which lab/section/exercise/tasks and your suggestions, so that we can look into the area where improvement is needed.

**Comment by houbena** [comment]
There are tons of issues.
My expectation is that if a new solution is implemented (here CloudSlices), the related content should be updated systematically by its developer before releasing. Later comes the role of the end users of that solution (trainers and learners) to report issues and improvements. And not the other way around.
What's happening now is that we're increasing the trainer's load of helping individual learners go around issues related to the outdated instructions. And we're doubling that load by asking them to report exactly the issues.

I believe a systematic scan and update of the content should be done on the first place. Contributions and improvement suggestions from the trainers come on the stage after.

**Comment by JeffKoMS** [comment]
@houbena Please file a bug with the Lab Hosting provider you are using when these errors are happening. We are providing instructions based on a VM/Azure Pass experience. The Lab Hosting provider is changing the target environment (to CloudSlice) and is responsible to adjust the lab steps to fit their particular implementation.
