### ISSUE TITLE
Lab 1 "Exercise 2: Build a front-end web application by using Azure Web Apps" image could not resolved

### ISSUE THREAD

**Issue by ChangeTheCode** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#534]
In the capital "Exercise 2: Build a front-end web application by using Azure Web Apps" could the image `![Create web app blade](./media/l01_create_a_front_end_web_app.png)` not resolved 

[Link to section](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_lab_01.md)

![image](https://user-images.githubusercontent.com/16823701/182547475-3b977ab7-6f2c-4e13-891c-42914ea00fdc.png)

**Comment by akjal** [comment]
Hi, Did you configure the ApiUrl settings value of this website as described below. (The ApiUrl value should be the URI of the API created ,imgapi, in the Exercise 1  .
![image](https://user-images.githubusercontent.com/15933669/183291655-ff843a56-edaa-495e-b72f-9018c88746f1.png)

**Comment by ChangeTheCode** [comment]
Sorry but I didn’t get your point. I just mentioned that this markdown link isn’t working like expected. The image isn’t shown.

**Comment by msftnutta** [comment]
@ChangeTheCode thanks for opening this issue. I've checked and I can see the screenshot. Please see the screenshot I attach below. 

![image](https://user-images.githubusercontent.com/98095529/183330704-46130a03-3ca1-4497-b326-7e7f5a0a9b4e.png)

Please let us know if you still see this, otherwise, we will move this issue to the close stage, thanks.

**Comment by akjal** [comment]
> Sorry but I didn’t get your point. I just mentioned that this markdown link isn’t working like expected. The image isn’t shown.

My bad. I got your question wrong. When you mentioned 'image could not be resolved' I thought you were referring to the imageweb application in this Lab exercise was not able to communicate to the imgapi . It is just a coincidence that the Lab is all about image uploading and stuff like that and you encountered an image related issue. Sorry for the confusion.!

**Comment by ChangeTheCode** [comment]
@akjal fine no problem 

@msftnutta  wired now it is also display by me. Sorry for creating this issue. I will close it
