### ISSUE TITLE
Lab 11: Publish-AzWebApp: Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#541]
# Module: 00
## Lab/Demo: 11
Exercise 3
#### Step: 15

Description of issue

In this step I consistently get an error: "...Publish-AzWebApp: Operation returned an invalid status code 'NotFound'..."

![image](https://user-images.githubusercontent.com/49700217/184232277-deac9f2f-c240-419a-978a-62c0be2c981d.png)

Repro steps:

1. Follow steps as written
2. I've verified I am using the new VM, new .md, and new /Allfiles using .NET 6.0
3. I can never rule out user-error, but this is the 3rd fresh run-through of this lab with identical error behavior.
4. Uncertain what might be the issue.

**Comment by JeffKoMS** [comment]
Need to update steps to use the full path of the .zip file. Powershell defaults to the c:\windows\system directory to look.
