### ISSUE TITLE
Instructions correction

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#546]
# Module: 06
#### Step: 02

Description of issue
Exercise 2, task 1, step 2 mentions running commands to CD into a folder which has not been created yet.

Repro steps:

1.
1.
1.

**Comment by msftnutta** [comment]
@davecatt thanks for opening this issue, however, we strongly recommend cloning the github repo prior to the lab, and that's how you will get all the lab files in a folder AllFiles > Labs which means, a folder 'OIDCClient' is already created there.

![image](https://user-images.githubusercontent.com/98095529/187384698-2134acaa-cb5c-4501-afbb-836bf67b6f1f.png)

**Comment by msftnutta** [comment]
close , working as designed.
