### ISSUE TITLE
Lab 12 : Unable to create Akamai CDN profile

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#550]
# Module: 12
#### Step: 03

Description of issue
Unable to create Akamai CDN profile, getting the following error.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"Akamai CDN profiles cannot be created with a PayAsYouGo account."}]}

![image](https://user-images.githubusercontent.com/47213023/187470935-31685d59-908a-463a-9304-6491cb0459cb.png)

Please update the instructions accordingly. 
Thanks and Regards.

**Comment by msftnutta** [comment]
Hi @junnhssn thanks for raising this issue, however, this looks like the current Azure - Akamai limitation according to this [link](https://docs.microsoft.com/en-us/azure/cdn/subscription-offerings).

In this scenario, we could not list down all the current limitations to our lab instruction and given the fact that all learners can freely use any subscription, this looks to me like it's the learner's responsibility to check Azure service limits and quota for the subscription that learner uses.

However, we're considering whether to add one section informing about Akamai - Pay-As-You-Go into our lab instruction.
