### ISSUE TITLE
Akamai CDN

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#551]
# Module: 12
## Lab/Demo: 12

Description of issue : Akamai not available.

So, I see in #550 @msftnutta commented as follows:

"In this scenario, we could not list down all the current limitations to our lab instruction and given the fact that all learners can freely use any subscription, this looks to me like it's the learner's responsibility to check Azure service limits and quota for the subscription that learner uses.

However, we're considering whether to add one section informing about Akamai - Pay-As-You-Go into our lab instruction."

I'm sorry, but as an MCT, that seems like a copout and I'm frankly staggered at the response. 

Students attending this course will generally be using the Azure Pass ordered as part of the delivery or possibly a cloud slice lab. Yes, they can "freely use any subscription" but would you want a student using their own paid subscription or their organisations subscriptions? Of course not. 

The instructions **should** be changed to indicate that the Microsoft Standard profile is the only one that can be chosen and the lab steps modified accordingly.

**Comment by msftnutta** [comment]
thanks for your suggestion @WigF1 , we're now considering making some modifications for this lab.

**Comment by msftnutta** [comment]
@JeffKoMS  Can we have our lab instruction suggest using other CDNs on Azure instead of Ekamai?
