### ISSUE TITLE
Lab Virtual Machine Setup update

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#552]
# Module: 00
#### Step: 00

Description of issue
Can you please update the lab.md file with the updated installations and versions (.NET 6 SDK).

Repro steps:

1.
1.
1.

**Comment by msftnutta** [comment]
@JeffKoMS Can you advise if we should put the link about the .NET runtime instllation?

**Comment by JeffKoMS** [comment]
I think we can simplify the lab.md file and just include the information on the tools installed and at some point in the future deprecated. All of that information is in the lab build guides available on the download center. But, the tools information may be valuable to people who are doing labs outside of a classroom environment.

**Comment by JeffKoMS** [comment]
Fixed.
