### ISSUE TITLE
Lab 07 UI Changed Keyvault new Objects section

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#553]
# Module: 07
#### Step: 04

Description of issue
Exercise 2, Task 2, step 4
On the Key Vault blade, select the Secrets link in the Settings section. No longer exist in settings, it has moved to Objects
Repro steps:
![image](https://user-images.githubusercontent.com/59872097/188893416-7b2830bb-b3e3-433d-8409-bc2f4aa5cb76.png)

1.
1.
1.

**Comment by msftnutta** [comment]
Thanks, @guthubcloudittogether  I've created a pull request to fix this issue.

@JeffKoMS  please help to review the pull request #555
