### ISSUE TITLE
Lab 07 - Exercise 2, Task 3 step 4 Access Policies moved

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#554]
# Module: 07
#### Step: 04

Description of issue
Exercise 2, Task 3, step 4
This is no longer under settings, moved to overview
![image](https://user-images.githubusercontent.com/59872097/188894333-8d9d1898-cfff-4a05-930e-23ede4b0ba79.png)
![image](https://user-images.githubusercontent.com/59872097/188894454-3b2d838a-12d6-4ddb-bcd1-ece3c581744a.png)

Repro steps:

1.
1.
1.

**Comment by msftnutta** [comment]
thanks for raising this issue @guthubcloudittogether the fix is included in #555 

Hi @JeffKoMS Please help to review the pull request, thanks.

**Comment by JeffKoMS** [comment]
Fix is merged.
