### ISSUE TITLE
Lab 09 - Exercise 3, Task 1 step 6 wrong NuGet package name

### ISSUE THREAD

**Issue by egbakou** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#557]
# Module: 09
#### Step: 06

Description of issue
Exercise 3, Task 1, step 6
The NuGet that is installed  is `Azure.Messaging.EventGrid`, not ` Microsoft.Azure.EventGrid`.
![image](https://user-images.githubusercontent.com/26142591/192109634-19ad5a6d-e5d4-4418-b878-9d00dfccee22.png)

Repro steps:

1.
1.
1.

**Comment by egbakou** [comment]
I've submitted a PR #556

**Comment by msftnutta** [comment]
thanks, @egbakou for raising this issue together with the pull request. let us check the pull request and we will merge it if it works.
