### ISSUE TITLE
When creating a storage account, Review + Create button and tab renamed to Review 

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#559]
# Module: All that create Storage Accounts
### Description of issue

When creating a storage account, the [Review + Create] buttons and tabs have been renamed to [Review].  Currently, it looks like this only affects the creation of Storage Accounts, but this may be a preview of what is going to change across all of Azure.  The directions and screenshots should be reviewed and corrected.

![image](https://user-images.githubusercontent.com/89028299/193620400-09d41220-dea8-4326-ab3b-f84598ef4a09.png)

**Comment by msftnutta** [comment]
thanks for raising the issue and a pull request provided by @rob-foulkrod ill work on this and get the screenshots updated as it still needs to follow the guidelines like the name of the resource group, subscription name, etc..

**Comment by JeffKoMS** [comment]
@msftnutta @rob-foulkrod  I'm not seeing this change for storage accounts in the portal. Wondering if this is a regional thing, been seeing lots of differences between portal experiences in EU vs. US.

![image](https://user-images.githubusercontent.com/25939240/194163653-f583eab0-b6b5-4e77-9d9c-5da7c867a602.png)

**Comment by rob-foulkrod** [comment]
You are correctly seeing the NEW text. It used to be 'Review + create'

**Comment by msftnutta** [comment]
@JeffKoMS  I checked and the changes by @rob-foulkrod (Thanks Rob) looked good, so I merged it and created another Pull request  #563 to correct all the screenshots.
