### ISSUE TITLE
Module 02: Task 3: Create a function app

### ISSUE THREAD

**Issue by MarcosFerreira17** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#564]
# Module: 02
#### Step: 06

Description of issue:
The hosting option is no longer available in this session on the Azure portal, need to update lab.

[![asa.png](https://i.postimg.cc/X7KtQjbw/asa.png)](https://postimg.cc/mtDdrGhD)

**Comment by msftnutta** [comment]
thanks, @msftnutta for raising this issue, but as per what I've checked by using several credentials, and kinds of Azure subscriptions, and I could confirm that I can still see the hosting tab like the screenshot below

![image](https://user-images.githubusercontent.com/98095529/195227044-3371c8df-40ac-427f-b0c3-71d98e98c076.png)

I noticed that you use an Educational Azure Subscription which could have a slightly different UI than other kinds of Azure Subscription (as designed). but our lab instructions are designed according to at least Azure Pass subscription, Pay-As-You-Go, and pretty much other enterprise Azure subscriptions.

Could you help to check again within your portal by using another username/password and another Acure Subscription that you may have? Please also advise what Azure Subscriptions are you using.

Thanks.

**Comment by MarcosFerreira17** [comment]
Hello, I checked in my personal account and noticed that everything seems ok, apparently only in my student account that does not contain this option.

[![ss.png](https://i.postimg.cc/s2ZGHy94/ss.png)](https://postimg.cc/s2ZGHy94)
