### ISSUE TITLE
Lab 04 - Core SQL option renamed to Azure Cosmos DB for NoSQL

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#567]
# Module: 04
##### Step: 03

Description of issue
The *Core (SQL) - Recommended* option has been renamed. It is now *Azure Cosmos DB for NoSQL*.

**Comment by msftnutta** [comment]
thanks, @rob-foulkrod  for raising this issue + pull request. Ill merge this.
