### ISSUE TITLE
AZ-204_lab_04.md has incorrect screenshot (probably)

### ISSUE THREAD

**Issue by mykolaichuk** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#572]
# Module: 04
#### Step: 3,4

Description of issue

Repro steps:

Step 3 says 'On the **Select API option** blade, select **Create** in the **Azure Cosmos DB for NoSQL** box' but on the screenshot in step 4 we see the text 'Create Azure Cosmos DB Account - Core (SQL) and API Core (SQL).' Please, double-check it. Thanks in advance.

**Comment by msftnutta** [comment]
thanks @mykolaichuk  for rasing this issue, i've created a pull request and it's ready to be merged. 

@JeffKoMS  please help to review. Since the UI in cosmos db has some minor updates.
