### ISSUE TITLE
[Feedback] Lab 04 Diagram could be clarified 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#576]
![image](https://user-images.githubusercontent.com/64772417/202146377-2194cd62-4f5f-4dac-9354-de7591efce4e.png)

- I would delete AAD from the image, it just represents we login into the portal (no other lab diagram shows it)
- for image uploading the process is manual, but the JSON documents use a .net program for it. Referencing the .net program used could be useful (AdventureWorks.Upload)

![image](https://user-images.githubusercontent.com/64772417/202147802-551bbe20-4a2c-4478-96aa-74f0670c51a9.png)

**Comment by msftnutta** [comment]
Hi @JeffKoMS 

Here we have a good suggestion from @unaihuete93, Shall we update this diagram?

**Comment by msftnutta** [comment]
thanks for this issue @unaihuete93 we have discussed and decided to convert this into our future work item. 

there is no tentative date for this yet.

**Comment by msftnutta** [comment]
the future work item could be seen [here](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/projects/1) on our board.
