### ISSUE TITLE
Lab 4 CosmosDB - Screenshot update

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#578]
# Module: 00
#### Step: 00

Description of issue: the **"Review+Create** tab for CosmosDB suffered a small change 

Original
![image](https://user-images.githubusercontent.com/64772417/202470916-a1631105-0ae7-48d8-b8e2-b32bcf3ffd0f.png)
New
![image](https://user-images.githubusercontent.com/64772417/202470971-66c23d33-dd69-4c9a-bd16-72fd1977f0d0.png)

**Comment by msftnutta** [comment]
thanks @unaihuete93  the pull request with a new latest screen shot has been updated :)
