### ISSUE TITLE
Lab 12 - Simplify querying/verifying the registration state of the CDN provider

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#579]
# Module: 12
#### Step: 01

Description of issue
There are many obsolete steps shown to check simply if the CDN provider is registered or not. Learners struggle with finding the entry in an unsorted list. Please change the instructions to use the simple command:

az provider show --namespace Microsoft.CDN --query "registrationState"

to improve the experience here and simply see either registered or notregistered.

**Comment by msftnutta** [comment]
thanks, @mkennten  agreed with you that the steps could be simplified, I've created a pull request #583 for the update.
