### ISSUE TITLE
Lab 6 Feedback (some related to cloudslice/skillable)

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#584]
# Module: 06
## Lab/Demo: 06 Implement user authentication and authorization

Clarify this step: student open cloud shell with powershell. They need to open it on the lab VM with Admin rights:
![image](https://user-images.githubusercontent.com/64772417/203501396-d49a9f6f-e387-4e5d-b9bc-6e45e82ffa2d.png)

it has to be command prompt, not powershell (as it does not work for rmdir). By default powershell option is opened in windows terminal.
![image](https://user-images.githubusercontent.com/64772417/203501611-25f361b4-ffa4-4e16-b72d-9570e79f2cf8.png)

The could easily open the VS code with the selected folder, typing "code ." in command promt`p (we could skip steps 4-5-6). We should Include a warning for clicking "Yes, I trust the authors":
![image](https://user-images.githubusercontent.com/64772417/203502185-85b09806-d56a-4400-bb3d-e1bbb5222c93.png)
![image](https://user-images.githubusercontent.com/64772417/203502056-3b8b7c3d-96f7-4ede-bd0b-8c7c2b3f960d.png)

What do we mean by this sentence? I am only able to do it, if we right click on a folder (but cannot right click on the **OIDCCLIENT** level. Telling my students to click on **Terminal>New Terminal** and no need to **cd** into the folder again.

![image](https://user-images.githubusercontent.com/64772417/203505223-3e767cd1-c52d-443d-8792-b99c7d57352d.png)
![image](https://user-images.githubusercontent.com/64772417/203505817-f0d6de1f-cdb7-4fc1-939b-7c17abec88c0.png)
![image](https://user-images.githubusercontent.com/64772417/203506263-c6a0533f-8b9c-41fc-87c7-cb9b356497b7.png)

**Comment by msftnutta** [comment]
agreed @unaihuete93  I've created the pull request and merged it. I will check again how the code tab will be displayed in CloudSlice for `Command Prompt `vs `PowerShell`.

and I will submit the ticket directly to CloudSlice if the code block still says `PowerShell` while our steps are written in `Command Prompt`.
