### ISSUE TITLE
Lab 07 Key Vault access policy UI changed

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#585]
# Module: 07
#### Step: 00

Description of issue
The wizard to create an access policy has changed, lab steps should be adapted accordingly:
![image](https://user-images.githubusercontent.com/64772417/203813306-6a12cfaf-ea57-4be7-893a-49000f56ebf4.png)

Repro steps:

1.
1.
1.

**Comment by msftnutta** [comment]
Thanks @unaihuete93  i put in a minor fix which included in #583
