### ISSUE TITLE
Lab 09: Cloud Shell misspelled, simplification of the registerState query.

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#586]
# Module: 09
#### Step: 1-5

Description of issue

Cloud Shell is misspelled CLoud Shell.

While you are on this, please think of simplifying the steps as suggested in issue #579; replace the many steps by the following:
az provider show --namespace Microsoft.EventGrid --query "registrationState"

**Comment by msftnutta** [comment]
thanks @mkennten I've created a pull request to fix this issue.
