### ISSUE TITLE
Lab 09: SKU and Size ==> Pricing Plans

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#587]
# Module: 09
#### Step: 4

Description of issue

The Azure Portal UI has changed and does not depict "SKU and Size" anymore, it just has a Pricing Plans section with a property "Pricing plan". The new terms should be reflected in the instructions.

![image](https://user-images.githubusercontent.com/37703728/204748197-7399de04-15a0-4740-be36-72f14b0d3b7d.png)
![image](https://user-images.githubusercontent.com/37703728/204748228-b9736f87-2b8c-42ac-93b9-8a2f3670defb.png)

Btw: this affects several labs, not only this one.

**Comment by msftnutta** [comment]
thanks @mkennten I've created a pull request to fix this issue.

**Comment by msftnutta** [comment]
thanks @mkennten  this fixed by #589
