### ISSUE TITLE
Lab : 02 - Timer Triggered Function is deployed with Serverless/Consumption Plan

### ISSUE THREAD

**Issue by vishipayyallore** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#590]
# Module 02: Implement Azure Functions
#### Step: 00

Description of issue
In this Lab, we are creating Azure Function App with Consumption/Serverless Hosting Plan. We are creating A. Http Post Triggered Function, B. Http Get Triggered Function and **C. Timer Triggered Function**. We are verifying locally and deploying it to Azure too.

Timer Triggered Azure function will not get executed when we deploy it to Azure with a Consumption/Serverless plan. It will be better to split this Lab into two A. Consumption Plan for Http Triggered Functions, and B. App Service Plan to Timer Triggered Functions.

**Regards,
Swamy**

![image](https://user-images.githubusercontent.com/8255269/205429796-771d0238-f9b6-43d7-a190-1b582f1c9f1c.png)

**Comment by msftnutta** [comment]
thanks @vishipayyallore for opening this issue. 

I've checked and I could successfully deploy the Timer Trigger Function App by using the consumption plan. 

Is there any error that you've encountered?

**Comment by msftnutta** [comment]
move to close as I've not heard back from the previous inquiry.
