### ISSUE TITLE
deletion of RG

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#591]
# Module: 02
### Task: Last

Description of issue
The command for definition does not work for the Cloud Slice.

az group delete --name Serverless --no-wait --yes    

The name "Serverless" must be updated to the original group name. It should be stored in variables from the previous run.

**Comment by msftnutta** [comment]
I've submitted the ticket separately to CloudSlice, let's see if they could provide the fix and ill monitoring this. Thanks @true-while

**Comment by msftnutta** [comment]
![image](https://user-images.githubusercontent.com/98095529/206333052-a3217b6c-0ba3-4740-aa83-bc6c996d2249.png)

hi @true-while we got a confirmation from the CloudSlice team, they mentioned that the pink section had been highlighted as a screenshot above. So there won't be an additional modification for this deletion step.
