### ISSUE TITLE
Lab 08 set headers policy not working as the lab says it does

### ISSUE THREAD

**Issue by cedral** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#594]
# Module: 08
#### Step: 15

Description of issue
the set header policy on the APIM doesn't appear to be working. I have set one on both the inbound and outbound policy and the resulting headers are not present in either the echoed headers json or the response headers
Repro steps:
Follow Lab 08 to task 2 step 15. When source is missing from the response try adding a set headers policy to outbound and note it doesn't work either.

Here is a picture of my policies. 

![EchoHeadersPolicies](https://user-images.githubusercontent.com/3732140/206807927-80416cd5-8045-4c16-b172-20fbee9a6a74.png)

Here is a picture of the result. Also note the response headers are nothing like the ones in your picture at task 2 step 15. All those ocp headers are missing. 

![SetHeadersFail](https://user-images.githubusercontent.com/3732140/206807929-b104d590-99b4-4e08-a4b7-feba366a9412.png)

**Comment by WigF1** [comment]
It's because you set the backend URL as http when it shouled have been HTTPS. This is because of the backwards way the instructions tell students to get the URL.

**Comment by cedral** [comment]
Thank You. That fixed it.
