### ISSUE TITLE
Lab 06 Build FAILED.

### ISSUE THREAD

**Issue by t-anderson** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#595]
# Module: 06 Implement user authentication and authorization 
#### Step: 12

**Description of issue**
Build FAILED. When using the code block from Task 1 Step 12 the build fails with the below warning and errors:

```
F:\Allfiles\Labs\06\Starter\OIDCClient\Models\ErrorViewModel.cs(5,18): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. [F:\Allfiles\Labs\06\Starter\OIDCClient\OIDCClient.csproj]
F:\Allfiles\Labs\06\Starter\OIDCClient\Controllers\HomeController.cs(11,22): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\06\Starter\OIDCClient\OIDCClient.csproj]
F:\Allfiles\Labs\06\Starter\OIDCClient\Controllers\HomeController.cs(13,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\06\Starter\OIDCClient\OIDCClient.csproj]

1 Warning(s)
2 Error(s)
```

The code from Task 1 Step 12 is missing PropertyGroup items:
```
<Nullable>enable</Nullable>
<ImplicitUsings>enable</ImplicitUsings>
```
**Repro steps:**

1. Copy code from Task 1 Step 12 and replace the code in OIDClIent.csproj
1. Enter in previous UserSecretsId value
1. run dotnet build

**Comment by WigF1** [comment]
You're not supposed to copy the code, nowhere do we instruct students to do that.

I ran through it with 11 students this morning and it worked fine when following the lab steps as written using Skillable Labs.

**Comment by tinodo** [comment]
I know this is closed, but we have many students REMOVING the settings not shown. (E.g. ImplicitUsings and Nullable).
Removing the ImplicitUsings causes this issue.
The instructions need to be update to show the proper csproj content.
