### ISSUE TITLE
Minor correction - build not expected to succeed, but instructions state it should

### ISSUE THREAD

**Issue by RogerHowellDfE** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#597]
# Module: 04
#### Step: 11

Description of issue

This line states that there should be no build errors. 

https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/3beb8238d1f3d8bcc9c3390bb6aa78a93c74b2c7/Instructions/Labs/AZ-204_lab_04.md?plain=1#L339

```
1.  Observe the results of the build printed in the terminal. The build should complete successfully with no errors or warning messages.
```

Instead, I see build errors reporting that the `AdventureWorksCosmosContext` could not be found.

```
PS F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web> dotnet build
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  AdventureWorks.Models -> F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Models\bin\Debug\net6.0\AdventureWorks.Models.dll
  AdventureWorks.Context -> F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Context\bin\Debug\net6.0\AdventureWorks.Context.dll
F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(33,63): error CS0246: The type or namespace name 'AdventureWorksCosmosContext' could not be found 
(are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(34,9): error CS0246: The type or namespace name 'AdventureWorksCosmosContext' could not be found (are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(35,51): error CS0103: The name 'AdventureWorksCosmosContext' does not exist in the current context [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]

Build FAILED.

F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(33,63): error CS0246: The type or namespace name 'AdventureWorksCosmosContext' could not be found 
(are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(34,9): error CS0246: The type or namespace name 'AdventureWorksCosmosContext' could not be found (are you missing a using directive or an assembly reference?) [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\Startup.cs(35,51): error CS0103: The name 'AdventureWorksCosmosContext' does not exist in the current context [F:\Allfiles\Labs\04\Starter\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:02.06
```

This class is to be created on the next step in Task 2, suggesting that the build should not be expected to succeed prior to this point (e.g., Task 1).

https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/3beb8238d1f3d8bcc9c3390bb6aa78a93c74b2c7/Instructions/Labs/AZ-204_lab_04.md?plain=1#L341-L348

**Comment by msftnutta** [comment]
![2023-01-25 11_06_53-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/98095529/214471678-08a1b190-2d76-4952-926f-fd91a01e0b31.png)

thanks, @RogerHowellDfE for reporting this, but this seems to be working as designed. 

I've tried to reproduce it and the root cause of this is missing action from step 9 which tells us to change the directory to AdventureWorks.Context directory and applying the following commands as per step 9

`dotnet add package Microsoft.Azure.Cosmos --version 3.28.0`

**Comment by RogerHowellDfE** [comment]
> thanks, @RogerHowellDfE for reporting this, but this seems to be working as designed.
> 
> I've tried to reproduce it and the root cause of this is missing action from step 9 which tells us to change the directory to AdventureWorks.Context directory and applying the following commands as per step 9

Doh - apologies for the goose chase on what seems to be user error on my part!

Thank you for investigating and sharing back @msftnutta 😃
