### ISSUE TITLE
Should we move from Azure SQL Database to a flat file?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#60]
I would propose changing the lab to avoid use of the Azure SQL Database platform.

Reason: AZ-204 course material (PPTs, Skillpipe) has zero coverage of Azure SQL Database. This service is covered in DP-200, DP-201, DP-050, etc. Not in AZ-204. Students thus find the lab quite challenging and the references to Azure SQL Database quite unexpected.

Yes, I realize this change might involve essentially recreating the lab from scratch. I think it's justifiable give the benefits of aligning labs to course scope. 

I welcome everyone's feedback on this proposal.

**Comment by VitalyMCT** [comment]
Yes, local file is fine too.

**Comment by seesharprun** [comment]
While this issue is closed, we can still discuss the topic here. If an action item needs to be taken, we will reopen the issue.
