### ISSUE TITLE
Feedback: Add lab scenarios

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#601]
All labs have architectural diagrams but no written explanation of the scenario (why are we doing what is done in the lab?).

This would be helpful especially when going over the lab outside of a training with no one to explain it.

Example from another course:
https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_01-Manage_Azure_AD_Identities.html (see "Lab scenario)

**Comment by msftnutta** [comment]
thanks for this issue @mkennten  we have discussed and decided to convert this into our future work item. 

there is no tentative date for this yet.

**Comment by msftnutta** [comment]
the future work item could be seen [here](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/projects/1) on our board.
