### ISSUE TITLE
Lab 01: Wrong pricing tier for App Service Plan

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#605]
# Module: 01
## Lab: 01
###Exercise: 02
##### Step: 05

The default setting for an ASP is Premium V2 P1v2 and therefore the ManagedPlan is deployed in that pricing tier (instructions state to leave default).

In the above-mentioned step, the instruction shows to select "ManagedPlan (S1)" which is incorrect. This should be corrected by either omitting the tier or printing the correct default value. Or in the first step when the app service is created it should be stated not to pick the default but change the tier to S1. Then also the images match.

**Comment by msftnutta** [comment]
Thanks for this issue @mkennten 

however, the default OS for App Service - Code - .NET is Windows and the default pricing tier for Windows OS in App Service is Standard S1 tier.

So it looks like working as designed :)
