### ISSUE TITLE
Lab 10 - "Register the Microsoft.EventGrid provider"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#61]
This task in the lab only _verifies_ that the provider is registered, so the name is a little misleading.

Proposal:

1) Remove the task altogether, or
2) Change its title to better reflect contents. Ex. "Verify that the Microsoft.EventGrid provider is registered"

**Comment by seesharprun** [comment]
It looks like the task was update in #17 along with another similar task but the title was not updated.
