### ISSUE TITLE
lab 11 - Replace Connect-AzAccount with Login-AzAccount

### ISSUE THREAD

**Issue by arambazamba** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#616]
# Module/Lab: 11
#### Step: 09

Description of issue

Replace Connect-AzAccount with Login-AzAccount

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by msftnutta** [comment]
Thanks for the suggestion @arambazamba but I am not sure if there is a need to replace it with Login-AzConnect

I've checked the [Az-PowerShell 9.4.0](https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-9.4.0) and I don't see Login-AzConnect command listed there, although I could execute Login-AzConnect command.

Could you give more details on why Login-AzConnect should be used?

**Comment by msftnutta** [comment]
Closing this as we do not hear from you, feel free to comment if you find any necessary to do so :) @arambazamba 

@JeffKoMS  FYI
