### ISSUE TITLE
Lab 01 WebApp for API , default plan value is Premium

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#618]
# Module/Lab: 00
#### Step: 00

Description of issue

When creating the webapp for the api, on the section for the ASP, it tells to choose default value, in Skillable it gives premium as default. Later, when creating the webapp for the web part, it tells to reuse "managedPlan(S1)"

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by msftnutta** [comment]
thanks, @unaihuete93 i've created the pull request and merged it successfully.
