### ISSUE TITLE
Code problems in Lab 6

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#620]
# Module/Lab: 6
#### Step: 21

Step number 21 should read:
```
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));
```

Currently, it reads `Configuration.GetSection("AzureAd")` and not `builder.Configuration.GetSection("AzureAd")`

Repro steps:
 Just do the lab, and `dotnet run` will fail because of the code problems

### Relevant screenshots
![image](https://user-images.githubusercontent.com/44774639/225651103-a86a264d-7b64-4965-86c4-0234b5c4ba8e.png)

**Comment by msftnutta** [comment]
thanks, @tinodo yeah, I can confirm this issue. and ill create the PR to fix this.
