### ISSUE TITLE
Instructions/Labs/AZ-204_lab_06.md wrong ports in screen capture or steps.

### ISSUE THREAD

**Issue by maxtrainmike** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#622]
# Module/Lab: 06
#### Step: 05

Description of issue

Instructions in Step 2 use port 5001.
Screen capture shows port 44321.

**Comment by msftnutta** [comment]
Thanks @maxtrainmike for this, I've corrected it with the pull request.
