### ISSUE TITLE
Misleading instruction

### ISSUE THREAD

**Issue by Mammux** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#623]
# Module/Lab: 09
#### Step: 04

Description of issue

These instructions are misleading:

> Exercise 2: Create an Event Grid subscription
> 
> Task 1: Access the Event Grid Viewer web application
> 
> On the Azure portal's navigation pane, select Resource groups.
> 
> On the Resource groups blade, select the PubSubEvents resource group.
> 
> On the PubSubEvents blade, select the eventviewer[yourname] web app.
> 
> On the App Service blade, in the Settings category, select the Properties link.

The properties are actually not under the Settings category, they are found by using "Overview" link, and the field is called "Default Domain", not "URL".

### Relevant screenshots

**Comment by msftnutta** [comment]
Thanks, @Mammux  for raising this issue.

The easiest way to retrieve the URL (FQDN) of the App Services is in the Overview blade you have mentioned which is now the 'Default domain'

however, the instruction intends to let learners explore other blades, and 'Properties' is now listed under the Setting section in App Service. There is other important info about App Services such as IP addresses, resource ID, etc...
