### ISSUE TITLE
Instruction Lab09 / Architecture Diagram title wrong

### ISSUE THREAD

**Issue by erikvanappeldoorn** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#624]
# Module/Lab: 09

Description of issue

The application in the Architecture diagram that is sending the events to the Topic is called MessageReader. It actually shoud have be named: MessageSender or even better EventSender.

**Comment by msftnutta** [comment]
@JeffKoMS  Could you help to check this one, please ?
