### ISSUE TITLE
Bug on Lab 08: Create a multi-tier solution by using Azure services

### ISSUE THREAD

**Issue by renatocamara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#625]
# Module/Lab: 08
#### Step: 00

Description of issue:
When he try to test on APIM to call the operation Get Legacy Data, is receiving error 404 because for some reason APIM is cutting from the URL (http://httpapi[yourname].azurewebsites.net/) the prefix http. To solve this issue the web app name shouldn't have at the beginning of the name http.

**Comment by msftnutta** [comment]
The lab instruction suggests using 'httpapi' as a prefix for the app service's name and learners should suffix it by replacing '[yourname]' with the unique string which in this case, it suggests using the learner's name.

@renatocamara  Could you help to elaborate more? What challenges you encounter?

**Comment by msftnutta** [comment]
@JeffKoMS Renato has suggested to rename the prefix from **httpapi[yourname]** to **api-[yourname]** to avoid the confusion. agree ?

**Comment by renatocamara** [comment]
I tried to reproduce but no success. Please, disregard this issue.

**Comment by msftnutta** [comment]
thanks for confirmation @renatocamara
