### ISSUE TITLE
Lab 12 - Redundant step to get instrumentation key

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#63]
The following step can be removed as students are already asked to get this code earlier in the lab:

>Get the value corresponding to the APPINSIGHTS_INSTRUMENTATIONKEY application settings key. This value was set automatically when you built your web app.`

**Comment by seesharprun** [comment]
This step is to ensure students see the instrumentation key in both locations (App Insights blade, Web App blade). The redundancy is by design.
