### ISSUE TITLE
Update variable initialization

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#645]
# Module/Lab: 10
#### Step: 10 and 11

Description of issue
The variables client and sender have no initialization in steps 10 and 11, but in the final results is step 13, they are both initialized with `= default!`.

Steps 10 and 11 should be updated appropriately.

### Relevant screenshots

![image](https://user-images.githubusercontent.com/89028299/234618801-c30bdcc5-38b2-4f02-9023-8df57d42f31b.png)

**Comment by rob-foulkrod** [comment]
In addition, initialization has been added in Ex 3 Task 2 steps 3 and 5,
![image](https://user-images.githubusercontent.com/89028299/234620737-dc1e78c3-588b-4a81-ae9f-c3ce6c3c16a5.png)

 but they are initialized in the final result in step 9.
![image](https://user-images.githubusercontent.com/89028299/234620936-9ae69ccc-e304-4c6c-b01c-2132e59418a4.png)

**Comment by JeffKoMS** [comment]
Fixed in the 2023-april-updates branch
