### ISSUE TITLE
Is creating product necessary ?

### ISSUE THREAD

**Issue by Andriy-dev** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#65]
# Module: 09
#### Step: 00

Im trying to create a visual for Lab 09 but cannot understand a purpose of a "product" for API Management Service. Do we need to associate Api with it ? It seems to work even without association.

<img width="834" alt="logic apps" src="https://user-images.githubusercontent.com/15020899/85161933-818d9200-b22e-11ea-990c-bc0b55718660.png">

<img width="849" alt="Screen Shot 2020-06-19 at 1 15 08 PM" src="https://user-images.githubusercontent.com/15020899/85162223-fb258000-b22e-11ea-8b29-43e3ce386b41.png">

**Comment by seesharprun** [comment]
It’s a holdover from the old API management model. In the old model, you were required to create a product before adding an API to the product.

In the new (consumption) model, the product is no longer required.

This is worth removing from the lab.

________________________________

**Comment by seesharprun** [comment]
Resolved in 6911b53
