### ISSUE TITLE
Lab 11: Missing files in Starter folder 

### ISSUE THREAD

**Issue by abarberenaCPDS** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#652]
# Module/Lab: 11
## Description

The `/weatherforecast` path does not exist and causes an HTTP 404 error. There's no context or previous steps that suggest that this path was previously created.

While comparing the Solution Folder, I noticed that `WeatherForecast.cs` and `WeatherForecastController.cs` were missing.

The **Instructor-led** content labs also have the same issue.

Repro steps:

1. Follow the instructions of Task 03, Step 05

### Relevant screenshots

- This is the content of `AllFiles.zip`, the **Labs\11\Starter\Api** folder is empty.

> <img width="362" alt="image" src="https://user-images.githubusercontent.com/43246964/235811699-2ba2109c-c9eb-4a0a-82f6-175997c67710.png">

- This step in the lab just creates an empty API project:
> <img width="966" alt="image" src="https://user-images.githubusercontent.com/43246964/235811783-cd250151-f85d-4e54-80ec-0b743e8dac18.png">

- This step refers to the `/weatherforecast` path which does not exist.

> <img width="963" alt="image" src="https://user-images.githubusercontent.com/43246964/235811858-9ecb9381-dc56-484f-9f1e-1addf1041e18.png">

**Comment by msftnutta** [comment]
thanks, @abarberenaCPDS for opening this issue.

however, it's working as designed.

there is no need to have the code provided in the Starter folder as the steps provided in "**Exercise 2: Monitor a local web API by using Application Insights**" will generate the code which contains everything for this lab.

Code in Solution folder is just for a reference.
