### ISSUE TITLE
Lab05 / No more .NET6.0 on Cloud Shell

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#671]
# Module/Lab: 05
#### Step: 05

Description of issue
net6.0 is no more a valid option. It is no longer installed on Cloud Shell.
The lab needs to be reviewed. Not only this step. We also call .Net 6 on the docker file of the container, etc... 

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/11490197/82767da8-f7d5-4ba1-96a1-5df0b4c924fc)

**Comment by JeffKoMS** [comment]
Thanks for the notification. Am investigating to see if this is just a temp  glitch.

**Comment by msftnutta** [comment]
thanks @tiagocostapt  for rasing this, i can confirm that i encounter the same issue as well, so this needs to  be updated for dotnet7.

**Comment by msftnutta** [comment]
@JeffKoMS  I've created a pull request by changing from dotnet 6.0 to dotnet 7.0 including the DockerFile
