### ISSUE TITLE
Lab 07 - Select Hosting is part of the Basics tab

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#675]
# Module/Lab: 07
#### Step: 00

Description of issue
Select Hosting is now part of the Basics tab.
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/10166617/68b26dde-719c-47d6-a169-c6437c50bea0)

Repro steps:

Exercise 1: Create Azure resources
Task 4: Create a Function app
In the Azure portal, use the Search resources, services, and docs text box to search for Function App, and then in the list of results, select Function App.

On the Function App blade, select Create.

On the Create Function App blade, on the Basics tab, perform the following actions, and then select Next: Hosting:

1.
1.

### Relevant screenshots

**Comment by msftnutta** [comment]
thanks @molenaar for reporting this, It has been fixed.
