### ISSUE TITLE
Lab 07 - Create a secret, specify Secret Value instead of Value

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#676]
# Module/Lab: 07
#### Step: 06

Description of issue
Both the instructions as the screenshot should be updated. **Value** is now **Secret Value**

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/10166617/9e0707fe-9b68-490f-9eb2-e7e9cfd51f71)

Repro steps:

On the Create a secret blade, perform the following actions, and then select Create:
Setting	Action
**Value** text: box	Enter the storage account connection string that you recorded previously in this lab

1.
1.
1.

### Relevant screenshots

**Comment by msftnutta** [comment]
thanks @molenaar the fix is in.
