### ISSUE TITLE
Lab 11 - Exercise 3 - Task 1 - Step 17 - Web App showing Internal Error

### ISSUE THREAD

**Issue by suketunayak** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#688]
# Module/Lab: 11
#### Step: 17

Description of issue 
All my participants are getting below Internal Error when they are using Azure **Free Trial** Subscription  -
when they access - https://smpapi[name].azurewebsites.net/weatherforecast **Showing Internal Error**

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12823966/77f1867a-dbe9-4b8a-8839-f70d5801f37b)

**Comment by msftnutta** [comment]
Hi @suketunayak 

Does this happen only to Azure Free Trial Subscription?

How long learners been using that Azure Free Trial subscription and what pricing tier selected for App Service?

**Comment by msftnutta** [comment]
it looks to me like the XML used wasn't well-formed.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/98095529/de710d34-310f-4927-8fc0-9a6586193c2a)

so this is a common mistake, learners should ensure the correct XML syntax.

**Comment by msftnutta** [comment]
However, I created a pull request to fix the spacing for the XML. thanks @suketunayak for opening this issue.
