### ISSUE TITLE
Lab 07: Wrong tab name after Basic

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#695]
# Lab: 07 Access resource secrets more securely across services
#### Step: 03

Description of issue
"Hosting" is not the correct name of the next tab anymore, it is "Storage"

### Relevant screenshots
<img width="207" alt="image" src="https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/37703728/81b29f4c-b8f6-4990-a4ff-a811ac074d29">

**Comment by msftnutta** [comment]
fixed thanks @mkennten
