### ISSUE TITLE
Incorrect storage account

### ISSUE THREAD

**Issue by corey-aloia** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#7]
# Module: az-204
#### Step: 05

Description of issue
Here: https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_02_lab.md#task-3-configure-an-http-triggered-function

On step 5, It says `Storage account connection: Azure WebJobsStorage`. However this appears to create a new storage account and not use the existing one which we uploaded to. In order to make it work, I had to create a new connection, and map it to my existing storage account.
Repro steps:

**Comment by seesharprun** [comment]
When you created the function app, did you select your existing storage account: https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_02_lab.md#task-3-create-a-functions-app

The issue you are seeing typically occurs when a new storage account is accidentally created during the creation of the function app.

**Comment by corey-aloia** [comment]
@seesharprun feel free you close this issue if you say it should work. I have noticed the last couple of days that the azure UI has been super slow, and it seems to have something to do with our corporate wifi. So it very well could be that I didn't give the UI enough time. Thanks!

**Comment by seesharprun** [comment]
I can keep the issue open for a little while longer to give you a chance to try creating a function app using the existing storage account instead of a new one.
