### ISSUE TITLE
Lab 01 stopped working because of changes in How storage accounts are created by default. 

### ISSUE THREAD

**Issue by tibor19** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#71]
# Module: 01
#### Step: 06

Description of issue: 
Azure Storage has changed, and by default bloc containers do not allow public access anymore. 

Repro steps: 
1. To fix this, you need to go to Advanced tab and Enable Blob public access

**Comment by tibor19** [comment]
Several labs suffer from the same issue, so far Lab 3 is another one of them.

**Comment by seesharprun** [comment]
This is the list of labs that use Azure Storage and will need to be tested to see if they work with or without public access:

- [x] Lab 01: PaaS
- [ ] Lab 02: Functions
- [x] Lab 03: Blob Storage
- [ ] Lab 04: Cosmos
- [ ] Lab 07: Key Vault
- [ ] Lab 09: Logic Apps
- [ ] Lab 11: Queue Storage
- [ ] Lab 13: CDN

@tiagocostapt, @VitalyMCT, @MikeBazMSFT, @tibor19: You all deliver this course regularly. While I am testing these labs, if you notice anything else just add on to this thread so we can get it all fixed this week.

**Comment by microsmith** [comment]
I have updated Labs 1, 2, and 3. Can someone review them and merge them? Hope to do five or six more labs this weekend and all by the end of next week.

**Comment by seesharprun** [comment]
It looks like this was inadvertently solved by the product team per #89.
