### ISSUE TITLE
Lab04 Feedback 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#714]
# Module/Lab: 04
#### Step: 00

Description of issue
1. Many learners get issues by executing the dotnet commands in the incorrect path/project during lab. I would include a reminder/warning of the path to use everytime we execute a dotnet command.
2. It would be better to directly include the Context file created in Exercise 3. Does not provide value to create it and it is a source of many problems. 

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by msftnutta** [comment]
i agree with @unaihuete93  this lab 4 is a little complicated as there are a few application components for this lab.
