### ISSUE TITLE
Azure portal Menu changed Lab 02

### ISSUE THREAD

**Issue by anagilara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#722]
# Module/Lab: 02 Implement task processing logic by using Azure Functions
#### Step: 05 On the Function App blade, select the Functions option in the Functions section.

The interface has changed. Now there is not the option Functions -> Functions.
The functions now are listed in the Overview section.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/110118950/52afa07b-ea81-4d31-b9aa-c1d77ebcd9b2)

**Comment by msftnutta** [comment]
thanks, @anagilara for reporting this issue.
