### ISSUE TITLE
Lab 06: IN LOD - Issue with New User ( it doies not pre exist, neither we can create one) 

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#723]
# Module/Lab: 06
### ****_IN LEARN ON DEMAND_**** - The new user donot exist in the Microsoft Entra ID tenant as per instruction.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12583943/02bc3898-34b4-4960-a986-448c4d749dca)

**Comment by msftnutta** [comment]
thanks @prabhjotsinghbakshi for opening this issue, I've tried to test several times and I see that the user has been created successfully by CloudSlice. 

I will keep this open for now, see whether we encounter this problem, if not, i will close this issue.

**Comment by msftnutta** [comment]
so far, no one has reported the same issue, hence, moved to closed.
