### ISSUE TITLE
LOD lab - Subscription missing in Lab 11 ( Application Insight) 

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#727]
# Module/Lab: 11
#### Step: 03

Description of issue
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12583943/ea4bea9c-8ada-4c3b-b4e8-7e65ff7f3faa)

### Relevant screenshots

**Comment by msftnutta** [comment]
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/98095529/e15bd1ac-f68c-4baa-a5ec-44400aec38d2)

I've tested it today and I can see there is a subscription provided by CloudSlice. I think it's the transient issue from Skillable, you can terminate the CloudSlice lab instance and re-launch it,

Do you still encounter the problem? @prabhjotsinghbakshi

**Comment by prabhjotsinghbakshi** [comment]
This happened in the morning all the 20 participants from Avande ( Mainly from Australia and USA) faced this issue including me

tomorrow again we will try and will keep you posted


Regards,

Prabhjot Singh Bakshi


________________________________

**Comment by msftnutta** [comment]
thanks for confirmation, hence, moved to closed.
