### ISSUE TITLE
Storage Account is private by default

### ISSUE THREAD

**Issue by anagilara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#730]
# Module/Lab: 03
#### Step: 07

When trying to create a container from the console app in VS code, it generates an error, since the Storage Account does not allow public access. Currently the storage account is by default with private access. Therefore, there should be an extra step to Allow Blob anonymous access in the storage account, whether at the moment of creating the account or after it.
![lab0301](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/110118950/c66d92ce-0ec8-442e-a89a-d6475af847c4)
![lab0302](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/110118950/260c2180-0745-4b86-9bc9-108b9e28f5c1)

**Comment by msftnutta** [comment]
There is one step that must be done during the Storage account creation to enable anonymous access.

On exercise 2 > Task 2: Create a Storage account

`On the Advanced tab, ensure Allow enabling anonymous access on individual containers is checked. Check the setting if it is not enabled.`

Do you still encounter after you have done this step? @anagilara

**Comment by anagilara** [comment]
Hi msftnutta,

I see the step in GtHub. I think is not updated in the labs environment. I will report it over there. Thank you very much!
It works with that step in Excercise 1.

**Comment by msftnutta** [comment]
If you use CloudSlice, I can see the instructions there.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/98095529/c91612bf-ac79-4c8b-b9bc-9e48db14ec0c)

However, It looks fine now, I move it to closed.
