### ISSUE TITLE
Update Lab #3 Goals

### ISSUE THREAD

**Issue by sdeming6543** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#735]
# Module/Lab: 03
#### Step: N/A

Description of issue:
In the introduction description of the lab, reference is made to the lab taking the learner through the steps of lifecycle management and building/using a shared access signature - neither of which are in the current lab. The paragraph should be removed:

"Finally, to ensure compliance with company regulations, you will implement secure access by generating shared access signatures and data lifecycle policies. You will test access to the content through a static website as well."

**Comment by v-asamim** [comment]
Updated.
