### ISSUE TITLE
Missing line in Lab06

### ISSUE THREAD

**Issue by theDiverDK** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#737]
# Module/Lab: 06
#### Step: between 22 and 23

After step 22 I need to make 1 more change to Program.cs before being able to login.

Before the line: 
app.UseAuthorization();

In the Program.cs

I need to add:
app.UseAuthentication();

I was unable to login, before adding this line.

**Comment by v-asamim** [comment]
Hello @theDiverDK,   

I tested the lab 6 without encountering any issues or errors.  
The "app.UseAuthentication();" code is already included.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/111972688/7ab9c434-6e27-4306-a29b-4b12d562dddd)

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/111972688/3e1ff7d2-baa9-409c-bfc4-2a7f3ce3f7b0)

**Comment by theDiverDK** [comment]
Also when you follow the guidelines?
I can find it in the solution, but not when following the guide. (It might be I am overlooking something, I hope it's that :-) )

After 'dotnet new.....' program.cs contains: (have removed a lot)

`app.UseRouting();

app.UseAuthorization();

app.MapControllerRoute(`

But the line 'app.UseAuthentication()' is not mentioned in the lab guide:
https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_lab_06.md
