### ISSUE TITLE
Update instruction text to match screen

### ISSUE THREAD

**Issue by sdeming6543** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#741]
# Module/Lab: 04
#### Step: 04

Description of issue
The written instructions make reference to the "Public access level"
and the actual screen text is "Anonymous access level"

Repro steps:

1. Open any Storage Account
2. Create a new Blob Container

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/47194555/f1977678-8767-4c18-958c-b98791bdcf7c)

**Comment by v-asamim** [comment]
Hello @sdeming6543, 

we will update soon, thank you.

**Comment by v-asamim** [comment]
This is fixed.
