### ISSUE TITLE
Associate screenshot with instructions

### ISSUE THREAD

**Issue by sdeming6543** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#742]
# Module/Lab: 07
#### Step: 04

Description of issue
The screenshot included in Step: 04 represents the "Basic" tab and should really be associated with the instructions of Step: 03. Step: 04 is fine, it just doesn't correlate with the screenshot. In addition, the screenshot is out-of-date. The 2nd tab should be "Access configuration" and not "Access policy".

Repro steps:
N/A

### Relevant screenshots
<img width="285" alt="image" src="https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/47194555/4bdc80ee-8198-4970-9835-9c070f0fd894">

**Comment by v-asamim** [comment]
The instruction has been updated, thank you.
