### ISSUE TITLE
Missing null-suppression operators generating warnings in Lab 10

### ISSUE THREAD

**Issue by sdeming6543** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#744]
# Module/Lab: 10
#### Step: 03

Description of issue:
In the code block, on lines #15 & #18, the reference to "default" is missing the null-suppression operator "!". The previous code block in Exercise 2/Task 2/Step 3 does have the null-suppression operators included.

Repro steps:

#15 should look like:
static ServiceBusClient client= default!;

#18 should look like:
static ServiceBusProcessor processor = default!;

### Relevant screenshots

**Comment by v-asamim** [comment]
Lab 10 has been updated.
