### ISSUE TITLE
MSBuild error in adding container to registry

### ISSUE THREAD

**Issue by the-data-detective** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#75]
# Module: 05
#### Step: 3

Description of issue

unable to build container registry due to this error:

MSBUILD : error MSB1001: Unknown switch.
Switch: --out

For switch syntax, type "MSBuild -help"
The command '/bin/sh -c dotnet publish --configuration Release --out' returned a non-zero code: 1
2020/07/07 15:22:17 Container failed during run: build. No retries remaining.

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
There is a typo in your Dockerfile.

This line is incorrect in your Dockerfile:

```dockerfile
RUN dotnet publish --configuration Release --output out
```

It looks like your file has this incorrect content:

```dockerfile
RUN dotnet publish --configuration Release --out
```

**Comment by the-data-detective** [comment]
This must have been when copying text from the Lab Instuructions directly into Dockerfile. Thanks for clarifying.

**Comment by seesharprun** [comment]
Which version of the lab instructions did you use? It would be great for us to check for formatting issues.

**Comment by the-data-detective** [comment]
It was downloaded into a VM directly from Github, so it had to be the latest version. The lab itself provided the ability to auto insert text into the VM and there was another copy issue wuith the COPY statement when I used it. I ended the lab, so there isn’t a way to validate what went into the Dockerfile, but I imagine it was due to the auto-insert function and not the syntax.

Jason Richards
[cid:image005.png@01D65451.FD220E40][cid:image006.png@01D65451.FD220E40]

M) 217-816-5452

Github<https://github.com/the-data-detective> | Blog<https://medium.com/@jasonrichards911> | LinkedIn<https://www.linkedin.com/company/68196904> | Website<https://thedatadetective.net>

**Comment by seesharprun** [comment]
Thanks for that explanation as that helps clear things up a lot!
