### ISSUE TITLE
Lab 4, Exercise 2, Task 3, Step 6.

### ISSUE THREAD

**Issue by Yiizo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#750]
# Module/Lab: 04
#### Step: 06

Description of issue
"dotnet add package Microsoft.Azure.Cosmos --version 3.28.0"

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/98825246/b00d75c9-761e-436c-9a58-409a9d5eb027)

**Comment by JeffKoMS** [comment]
Can't reproduce the issue. 

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/25939240/767bb9e0-5012-43ca-8095-62d43a680877)
