### ISSUE TITLE
Lab number 5: Link to download folder is missing

### ISSUE THREAD

**Issue by pushkarsule** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#754]
# Lab: 5
#### Step: Download folder

Description of issue
The link to download folder is missing
Repro steps:

1.Start lab number 5. Link to download button is missing.

### Relevant screenshots

**Comment by v-asamim** [comment]
@pushkarsule Thank you for reporting this issue. Currently, the download link is active and working properly. 

<img width="212" alt="image" src="https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/111972688/61915b2f-2421-4cc6-a381-66e2b0423543">
