### ISSUE TITLE
Lab 3: create console app fails

### ISSUE THREAD

**Issue by pushkarsule** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#755]
# Lab: 03

Description of issue
the command "dotnet new console --framework net8.0 BlobManager --output ." Fails
The fix is to use net6.0 framework.
Repro steps:

1.dotnet new console --framework net8.0 BlobManager --output .
1.

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/10298700/636425ca-5e74-4767-90cc-6b96c4cb0c54)

**Comment by KoalaBear84** [comment]
It depends on your environment. [.NET (Core) framework 8.0 SDK](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks) should be installed.

**Comment by rramoscabral** [comment]
Hello @pushkarsule,  KoalaBear84 answer is correct. 

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/9170251/2db9d707-8579-411a-a571-ad69e426fc91)
