### ISSUE TITLE
Lab 13, Exercise 5, Task 2 not correct

### ISSUE THREAD

**Issue by KoalaBear84** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#759]
# Module/Lab: 13
#### Step: 1

Description of issue

Repro steps:

The whole "Azure CDN" part is gone.

### Relevant screenshots

https://learn.microsoft.com/en-us/azure/cdn/cdn-add-to-web-app

This whole screen is replaced with a new UX, only "Azure Front Door" is available, but it does not show the just created profile.

**Comment by v-asamim** [comment]
@KoalaBear84 The instructions for the lab have been recently updated.
