### ISSUE TITLE
CDN is no longer part of a Web App's Network Settings.

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#762]
# Lab: 13
#### Step: 02

The lab reads:

On the **Networking** blade, in the **Inbound networking features** box, select **Azure CDN**.
This setting is (no longer) here.

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/44774639/5d9334cb-a45b-4078-b0a0-a1dd5acd9e95)

**Comment by v-asamim** [comment]
@tinodo  The instructions for the lab have been recently updated.
