### ISSUE TITLE
Lab 02 issues

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#767]
# Module/Lab: 02

Description of issue

Given the lab now uses CURL instead of HTTPREPL, the instruction for Exercise 3, Task 3 should no longer say "Test the HTTP-triggered function by using httprepl"

Also, in the same Task, we instruct students to open Windows Terminal, which will default to Windows PowerShell. Thus, all curl commands will fail as curl is an alias for Invoke-WebRequest

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/fc46b2a6-8dfb-4128-9482-60a63dd118b7)

Task 3 should probably instruct students to open CMD and run the curl statements from there. Exercise 5, Task 5 should also do the same as this also uses curl.

Also, the overview video is now out of date given we don't use HTTPREPL.

**Comment by JeffKoMS** [comment]
Merging your PR to main at end of day today.
