### ISSUE TITLE
LP 9 has outdated example screenshot for creating a web app

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#768]
#### Step: 04

Description of issue
Step 4 instructs you to create a web app with the default in-place for pricing plan. The current default is now P1V3, but the existing example screenshot in the manual has P1V2 listed, which will fail [p1], and we've had a few instructors report getting caught on matching the screenshot exactly. Requesting screenshot be updated to reflect the current default and necessary pricing plan of P1V3 [p2].

### Relevant screenshots

[p1]

![image-1](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/94069201/5be5198c-da8b-40ff-bb49-68d1404a757a)
![l09_create_web_app](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/94069201/87c0bfc5-7c69-46f8-82fa-69454c7e014d)

[p2]

![image-1](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/94069201/5d7c66c1-9c4e-4ada-a264-34f490da58a0)

**Comment by JeffKoMS** [comment]
Fix will go live later today.
