### ISSUE TITLE
Lab 02 - Trigger implementation incorrect

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#769]
# Module/Lab: 02
#### Step: 05

Description of issue

After running Task 1, Step 3 to create a new Timer trigger, the code implemented does **not** match the code listed for Ex 5, Task 2, Step 5. 

The line numbers on Step 6 also doesn't match the code displayed.

So, which is correct? the default timer implementation or the one displayed?

This is the default implementation
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/9c19ef9b-0316-4811-aa0d-d483d37ef76e)

**Comment by JeffKoMS** [comment]
Merging your PR at the end of the day today.
