### ISSUE TITLE
Lab VM update

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#770]
As the lab VMs are now Windows 11, any and all references to Windows 10 should be removed from lab steps. 

Also, 'Windows Terminal' isn't called that any longer. It is 'Terminal' in the current lab VM image. All references to 'Windows Terminal' on the taskbar need to be changed accordingly also.

**Comment by JeffKoMS** [comment]
Fixed. Will go live this Friday.
