### ISSUE TITLE
Lab 02 - Isolated warmup

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#771]
# Module/Lab: 02
### Task: 02

Description of issue

Due to the labs now using the isolated model, the warm-up takes a significant amount of time. 

It is approximately 1-2 minutes after Task 1, Step 6 finishes before the functions will show in the Azure portal. 

Even once the functions appear, Task 2 cannot be completed, because all students see when navigating to the 'Test/Run' page is a blank page with a spinning progress indicator.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/1b3402f2-ea36-488e-b7ad-c9fe319a847f)

It would seem that when creating the function app initially, the Azure portal defaults to .NET 6 Isolated, we then deploy a .NET 8 Isolated.

Defaults
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/b68b64ef-0bf0-4dcc-a8ff-d9b9b5791f36)

We may need to change to .NET 8 in order for the Test/Run to work correctly.

**Comment by WigF1** [comment]
I am running through all the labs atm for PR purposes. This is what happens when you run the publish command per Exercise 6, Task 1, Step 6.

It shows that a default is being changed to .NET 6. 

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/4c2056fb-d632-42bf-9b28-a83319f5edb5)

Setting the version as part of the command forces the version to match the choices when creating the function app earlier.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/f6ad070a-0055-4b22-a88b-07dcfa99bda4)

Doing this resolves all the problems!

**Comment by rob-foulkrod** [comment]
Lab instructions are fine. Azure Function Core tools v4.0.5455 and earlier will incorrectly detect the framework version and set it in the app. Version 4.0.5530 fixes this.

Lab Providers will want to update to version the 4.0.5530 version of the Func Core Tools to avoid this problem
 
[Comparing 4.0.5455...4.0.5530 · Azure/azure-functions-core-tools (github.com)](https://github.com/Azure/azure-functions-core-tools/compare/4.0.5455...4.0.5530)

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/89028299/d0943b12-d9d3-4966-9b04-bee5f22cf8a8)

**Comment by JeffKoMS** [comment]
Merging your PR with the fix later today.
