### ISSUE TITLE
AZ-204_lab_07 - incorrect runtime value

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#772]
# Module/Lab: 07
### Task: 03

Description of issue

The code snippets for local.settings.json in Step 5,6,7 have an incorrect worker runtime specified. 

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/1c0a5572-f652-4baa-88df-fb8a785366fe)

It should be dotnet-isolated.

**Comment by JeffKoMS** [comment]
This fix was included in your PR and will go live later today.
