### ISSUE TITLE
Requesting permission to have modules pre-installed on VS code on machines for labs

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#775]
#### LP 2

Skillable has AZ-204 on LP 2, Every time you open VS Code and then a project, it installs the required modules like Razer support / C# support etc. I'm requesting permission to update the VM to install all of the necessary modules for VS Code so students and instructors don't have to spend time doing it during their classes.

![image001](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/94069201/cfebc5a6-001c-49f3-8ac0-a21d3adef56c)

**Comment by JeffKoMS** [comment]
@SkillableBB Can you detail more of what you mean by "install of the necessary modules" - not sure what modules you would install. The telemetry download is initiated by .NET based on the project type.  I guess we could try to load every project in the VM and then save the state - but it's likely it will still go out and pull down a more recent version of the telemetry info if available. We could also opt out of the telemetry by changing an environment variable and reinstalling .NET 8. Not sure what impact that would have on the intellisense provided by the C# dev kit...

**Comment by JeffKoMS** [comment]
Haven't heard back, so closing.
