### ISSUE TITLE
Lab 02: Function in Linux OS gives issues 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#777]
# Module/Lab: 00
#### Step: 00

Description of issue
Cannot execute **Test/Run**. Screenshot on resource creation shows Windows but instructions mention Linux. Learners with Linux could not test the function.
![Screenshot 2024-02-26 163035](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/64772417/e4219f0e-2244-4a16-a883-650398428865)

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by WigF1** [comment]
See my #771

**Comment by JeffKoMS** [comment]
Closing since it's a dupe.
