### ISSUE TITLE
Lab 2: Operation System for Function App should be Windows instead of Linux.

### ISSUE THREAD

**Issue by renatocamara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#780]
# Module/Lab: 02
#### Step: 05

Description of issue
The Operation System should be Windows instead of Linux. If you choose Linux, you will hit on AZ-204_Mod02v1 policy validation error.

**Comment by JeffKoMS** [comment]
@renatocamara I can't duplicate the issue. The steps work correctly for me, so it may be a policy issue in the lab hosting provider used for that lab delivery. Please follow up with them on the issue.
