### ISSUE TITLE
deployment has failed with the followiong error: minimum TLS version is not supported

### ISSUE THREAD

**Issue by AlanJ97** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#782]
# Module/Lab: 09
#### Step: 05

Description of issue
I am a Microsoft trainer and my students are having an issue, When they try to create the subcription  in the Event Grid, they have the error "deployment has failed with the followiong error: minimum TLS version is not supported", we tried rebooting the labs, changing the TL version and nothing works. But is weird that 4 students did not have the issue, only 2 of them didn't complete it because of this error.

Repro steps:

1.
1.
1.

### Relevant screenshots
<img width="252" alt="ERRORS" src="https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/51300800/84bd0a37-3a71-47af-979f-e229ce3ed965">

**Comment by JeffKoMS** [comment]
@AlanJ97 I'm going to flag this as "more info needed" more as a tracker. Please LMK if you see this issue impacting random students in future deliveries. I'm wondering if this was just a glitch since it worked for others.

**Comment by JeffKoMS** [comment]
Closing since no further occurrences have been reported.
