### ISSUE TITLE
LP 12:  Azure UI has changed for Web App

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#785]
# Module/Lab: 12
#### Step: 04 & 5

Description of issue

Azure Web App UI has changed since original course release, several steps that could use some clarifications/updates.

- In Step 4, in the Publish section, 'Select Docker Container' is now just 'Container':

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/49700217/b523728c-a794-4e8d-b1d5-a6a9638b8a71)

- In Step 5, the 'Docker tab' is now just 'Container' tab.  Also, I am not certain the 'Registry server URL' may or may not be populated automatically, but it might be good to clarify an exact value needed there, if any:

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/49700217/a60794c0-79e0-45f6-971b-a59a9a0b6fbc)

**Comment by JeffKoMS** [comment]
Thanks, I'll get this updated shortly.
