### ISSUE TITLE
Lab 01: Creating Azure Apps Service Web Apps - Instructions should be update

### ISSUE THREAD

**Issue by renatocamara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#786]
# Module/Lab: 01
#### Step: 01

I noticed that on Exercise 1 - task 5, step 1 the instructions should be update because Application settings was moved from Configuration to Environment variables.

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/833283/bdd1aeb7-a6be-4b66-8aaa-b34f51ec36cd)

**Comment by JeffKoMS** [comment]
It looks like they're doing some A/B testing, and that hasn't changed for everyone.  Is anyone seeing this outside of the cloudslice environment?

**Comment by JeffKoMS** [comment]
PR #788 resolved this.
