### ISSUE TITLE
Cloud Shell - Multiple labs

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#797]
It seems the 'new' cloud shell has been rolled out globally. 

Instructions should be updated to match the current UI 

https://learn.microsoft.com/en-us/azure/cloud-shell/new-ui-shell-window

Also, the creation process is now different also, so those steps need to be changed.

The UI is different, but the first step is still to choose either Bash or PowerShell. Thereafter the UI changes.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/f7784f15-9c4d-4d59-83d0-be30f29c3950)

Choose mount storage account, select the subscription from the dropdown, then select Apply.

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/814f8134-142c-4e23-bcce-de0f16bd1b5f)

Select 'We will create a storage account for you', select Next

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/6a9cc1c0-60f7-43c0-b24c-f63694488289)

Now wait for provisioning:

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/ead37779-da18-407c-b29d-4a5493c975e6)

**Comment by JeffKoMS** [comment]
@WigF1 I'll get these updates made next Monday the 20th.
