### ISSUE TITLE
Lab 7 : obsolete

### ISSUE THREAD

**Issue by madhatterxyz** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#814]
# Module/Lab: 07
#### Step: 03 and 04

Description of issue
- https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/media/l07_create_function_app.png is blank

- There is no storage tab in the Function App creation.

**Comment by msftnutta** [comment]
thanks , and this was included with PR #822
