### ISSUE TITLE
LP 9 has outdated example screenshot for creating a web app, container tab

### ISSUE THREAD

**Issue by renatocamara** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#815]
# Module/Lab: 09
#### Step: 05

Description of issue

Repro steps:

1. In the container tab, the screen is different from the instructions.

### Relevant screenshots
![image](https://github.com/user-attachments/assets/f02ced63-a965-4f82-a870-a8be5f3f269f)
![image](https://github.com/user-attachments/assets/e2d748e1-f127-47fe-afe1-260a1ac84621)

**Comment by msftnutta** [comment]
this was fixed by #822 , thanks for reporting this
