### ISSUE TITLE
Updated Storage Account Interface not reflected in Lab Steps

### ISSUE THREAD

**Issue by sdeming6543** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#817]
# Module/Lab: 01
#### Step: 03

Description of issue
While creating the Storage Account, we now need to provide information on the Primary service and the Primary workload

Repro steps:

1. Create any Azure storage account
2. The new Primary service prompt appears - when you select Azure Blob Storage
3. Then the new Primary workload prompt appears - I've been advising the students to choose "Other"

### Relevant screenshots
![image](https://github.com/user-attachments/assets/aa5bc085-13ab-4dbc-a13a-ca3a3233457c)

**Comment by WigF1** [comment]
We don't need to specify anything for the primary service or workload. They are not required components. 

In saying that, we **should** add a note letting students know to ignore them.

**Comment by JeffKoMS** [comment]
Added ignore the primary service instructions. Primary workload will be added later - don't know if this is a preview feature or not. It isn't showing up for me.
