### ISSUE TITLE
Lab 01 - Exercise 2: InvalidOperationException: Invalid Request URI in Contoso Photo Gallery Web App Deployment

### ISSUE THREAD

**Issue by gisioraelvis** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#818]
# Module/Lab 01: Build a web application on Azure platform as a service offering
#### Step 21: In the Contoso Photo Gallery webpage

# Description of issue
Getting An unhandled exception occurred while processing the request when trying to access the front-end web app.

InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
System.Net.Http.HttpClient.GetStringAsync(string requestUri)
Web.Pages.IndexModel.OnGetAsync() in Index.cshtml.cs
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+NonGenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
Repro steps:
Click on the default domain to access the web the following error and stack trace is displayed on the page

### Relevant screenshots
![image](https://github.com/user-attachments/assets/f3e6563c-7c87-4c01-97f8-81158bd25df9)

**Comment by WigF1** [comment]
Your issue was the configuration didn't include the https:// per the instructions. Your MCT should have clarified this with you. It's not an issue with the labs. 

Could you kindly close the issue?

**Comment by msftnutta** [comment]
close as it's working as designed.
