### ISSUE TITLE
Lab 11 UI change: "Configuration" is now "Environment variables"

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#820]
# Module/Lab: 11
#### Step: 08 and 09

Description of issue
"Configuration" is now "Environment variables" in the portal UI.

8. On the App Service blade, in the Settings section, select the **Configuration** link.
9. In the **Configuration** section, perform the following a

### Relevant screenshots

**Comment by msftnutta** [comment]
this was fixed by #822 thanks for reporting this @microsmith
