### ISSUE TITLE
AZ-204_lab_02 misspelling "Consumpotion"

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#823]
# Module/Lab: 02
#### Step: 06

Description of issue

Misspelling:

On the Create Function App (**Consumpotion**) blade, on the Basics tab, perform the following actions, and then select Next: Storage: 

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by microsmith** [comment]
Misspelling: "Consumpotion"

**Comment by JeffKoMS** [comment]
Fixed, thanks.
