### ISSUE TITLE
Lab 02: Implement task processing logic by using Azure Functions

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#827]
Lab 02: Implement task processing logic by using Azure Functions
Exercise 4: Create a function that triggers on a schedule
Task 2: Observe function code
Step 5
![image](https://github.com/user-attachments/assets/7875eac9-4042-4c72-b84c-709be824509f)

**Comment by microsmith** [comment]
The lab instructions look correct in GitHub. This looks like a formatting issue in the lab host's lab steps.

**Comment by JeffKoMS** [comment]
Please log an issue with the lab provider.
