### ISSUE TITLE
API management lab - policy error

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#829]
# Module/Lab: Lab 08: Create a multi-tier solution by using Azure services
#### Step: 3

Description of issue

Region drop-down list | Select **any Azure region** in which you can deploy an Azure web app

This doesn't work. If you select for example canada as a region (which was the default suggested), the deployment fails. The policy will validate whether the web app is deployed in the same region as the location of the resource group. If not, it fails.

Please update the instructions:

Region drop-down list | **Select the same Azure region as your resource group location.**

### Relevant screenshots
![image](https://github.com/user-attachments/assets/60145ea7-7117-48fb-b131-c8383f4bf25c)

**Comment by JeffKoMS** [comment]
Fixed, but really if the ALH is imposing restrictions they should be altering the instructions to meet their particular implementations.
