### ISSUE TITLE
Lab 02 : Please correct the typo in Implement Azure Functions 

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#837]
# Module/Lab: 02
#### Step: 05

Description of issue
should be fixed.

<img width="955" alt="image" src="https://github.com/user-attachments/assets/35a154e8-c95a-42ff-8cea-4a7fcff4b37a">

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by JeffKoMS** [comment]
That's an issue with how the ALH implemented the instructions. Please open a bug with the lab hoster.
