### ISSUE TITLE
Issues running the functions in azure portal after building in dotnet isolated using local azure function core tools

### ISSUE THREAD

**Issue by aguluman** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#846]
# Module/Lab: 02
#### Step: 1 to 11

Description of issue
It does not work, because the local development of azure functions builds the project as "dotnet isolated" so the functions cannot be edited and tested on the azure portal.

Repro steps:

1. Deploy a dotnet isolated function project to GitHub
2. Go to the overview page and witness the created functions do not display there.

### Relevant screenshots
Message from copilot, using the ChatGPT o1 preview:
```
Since your project uses .NET isolated functions, you cannot use the Azure portal's "Code + Test" feature to edit or test the functions directly. However, you can still validate the deployment by invoking the function using tools like:

Postman: Send HTTP requests to your function endpoint URL.
Azure Function's URL: Directly call the function using the URL displayed in the Azure portal.
Local development environment: Use Visual Studio or Visual Studio Code to run and test your function locally before deploying.
You can find and invoke the function URL by navigating to your function app in the Azure portal and selecting the function's "Get Function URL" option.
```

**Comment by WigF1** [comment]
I ran through it with 10 students this week and it worked fine. 

You can absolutely test isolated functions in the Azure portal. We need some more details on "it does not work" to be able to assist your students.

**Comment by aguluman** [comment]
Thanks for your response.

Your fact assisted me in figuring out what was wrong.
It was a knowledge gap.

Cheers.

I am closing the issue now.
