### ISSUE TITLE
Problem Creating CDN Under Azure for Students License.

### ISSUE THREAD

**Issue by aguluman** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#848]
# Module/Lab: 12
#### Step: 07

Description of issue
```
Error details
Free Trial and Student account is forbidden for Azure Frontdoor resources.

 (Code: BadRequest)
```

The screenshot above shows why I can not create one.
Repro steps:
1. Same as described in the module.

### Relevant screenshots
The screenshot,

**Comment by WigF1** [comment]
You are not creating Front door resources in the lab. Also, the subscription used in the ALH labs is not a free trial or student account.

Please ensure you are only using ALH labs for yur deliveries.

This is not an issue with the labs.
