### ISSUE TITLE
Lab: Building a web application on Azure platform as a service offerings Student lab answer key   Issues

### ISSUE THREAD

**Issue by tanthiamhuat** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#85]
https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_01_lab_ak.html

I read that "Azure Storage and will need to be tested to see if they work with or without public access:", and "To fix this, you need to go to Advanced tab and Enable Blob public access". But I do not see any Advanced tab or Enable Blob public access. 
I find that public access for Blob is under Configuration, and it is Enabled.

Do I need to do the below steps also?
(i) Go to Storage Explorer (Preview)
(ii) Select the Container [images]
(iii) Manage Access
(iv) Superuser (Owner & Owning Group)
(v) Access: Read, Write, Execute
Does above give public access to the Blob images?

Lab/Demo: 01
Task: 6
Step: 16

Description of issue:
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202

Repro steps:
(1) In the appsettings.json, I modify the AccountName and AccountKey according to my storage.
(2) dotnet restore
(3) dotnet build
(4) above will create directory bin\Debug\netcoreapp3.0 under \allfiles-v20200629.03\Labs\01\Starter\API directory
(5) zip up that netcoreapp3.0 directory as api.zip
(6) Change directory to where the api.zip is located
(7) Did the deployment as instructed: az webapp deployment source config-zip --resource-group myresourcegroup --src api.zip --name imageapitest123
Before Step 7, I did the az login, az webapp list --resource-group myresourcegroup, az webapp list --resource-group myresourcegroup --query "[?starts_with(name,'imageapitest123')].{Name:name}" --output tsv

**Comment by seesharprun** [comment]
It looks like the first issue was inadvertently solved by the product team per #89.

The second issue is an unsupported path. We include pre-built zip file so you don't have to do a ``dotnet publish`` step in your lab instructions.
