### ISSUE TITLE
Lab 02: Synchronous Operations not Permitted

### ISSUE THREAD

**Issue by gerryaobrien** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#851]
# Module/Lab: 02
#### Step: 05

Description of issue
Because the lab steps prior to this exercise have the student set the connection string (Exercise 2, task 2, the function will generate an error indicating that synchronous operations are not allowed. Changing the code to run asynchronously is a workaround or a fix.

Repro steps:

1. Complete the lab steps as written up to this point.
1. When running the curl command in exercise 3, task 3, step 5, an error is generated indicating that synchronous operations are not permitted
1.

### Relevant screenshots

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Echo.cs file to use asynchronous methods for reading the request body and writing the response. This change addresses the issue where synchronous operations were not allowed, which was causing an error when running the curl command in exercise 3, task 3, step 5.

You can review changes in this commit: https://github.com/mark-addams001881/MicrosoftLearning-AZ-204-DevelopingSolutionsforMicrosoftAzure-851/commit/0ae49e257cf849c090b523bf64e283b91ab25b52.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by gerryaobrien** [comment]
This will solve the issue
