### ISSUE TITLE
Lab: Implement task processing logic by using Azure Functions Student lab answer key

### ISSUE THREAD

**Issue by tanthiamhuat** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#86]
https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_02_lab_ak.html

Lab/Demo: 02, 
Exercise 4: Create a function that integrates with other services
Task: 5
Step: 6

Description of issue
HTTP/1.1 204 No Content

Before the steps below, I performed the below steps as instructed:
Saving settings.json file to container named "content", 
![content](https://user-images.githubusercontent.com/9988941/87239176-a5638280-c43e-11ea-9f7c-6816183f94bf.png)
and 
Configure an HTTP-triggered function as attached below:
![Funclogic](https://user-images.githubusercontent.com/9988941/87239128-0a6aa880-c43e-11ea-91aa-b56ecf46836b.png)

Repro steps:
1) httprepl
2) set base https://funclogictest.azurewebsites.net
3) cd api
4) cd getsettinginfo
5) get
See attached file below
![AzureFunction](https://user-images.githubusercontent.com/9988941/87239003-5f0d2400-c43c-11ea-89de-a0eb43bf31e6.png)

**Comment by seesharprun** [comment]
We have seen this issue before. This typically happens when you create your Azure Function using a different storage account than the account you uploaded content to.

If this is not true, please re-open the issue.
