### ISSUE TITLE
Lab: Automate business processes with Logic Apps Student lab answer key

### ISSUE THREAD

**Issue by tanthiamhuat** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#87]
https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_09_lab_ak.html#exercise-3-use-azure-api-management-as-a-proxy-for-logic-apps

Lab/Demo: 09
Task: 00
Exercise 3, Task 4

Description of issue
E:\>httprepl https://prodapimthiam.azure-api.net/manual/paths/invoke
(Disconnected)> connect https://prodapimthiam.azure-api.net/manual/paths/invoke
Using a base address of https://prodapimthiam.azure-api.net/manual/paths/invoke/
Unable to find a swagger definition

https://prodapimthiam.azure-api.net/manual/paths/invoke/> get
HTTP/1.1 401 Access Denied
Cache-Control: private
Content-Length: 152
Content-Type: application/json
Date: Tue, 14 Jul 2020 10:05:51 GMT
WWW-Authenticate: AzureApiManagementKey realm="https://prodapimthiam.azure-api.net/",name="Ocp-Apim-Subscription-Key",type="header"

{
  "statusCode": 401,
  "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."
}

Repro steps:
Follow instructions from the top link.

**Comment by seesharprun** [comment]
This looks like a change to the service. For a quick resolution, we removed this task from the exercise.
