### ISSUE TITLE
Guidance AZ204

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#88]
# Module: ALL
#### Step: 00

Description of issue
Hello, I am looking for some guidance. I am intending on delivering the AZ204 course. I have up until now been delivering the AZ900 which is different as we know. I am looking for some guidance from a fellow MCT on some of the best approaches in delivering this course.

Slides, Demos and the balance between them. Any help would be appreciated email cloudittogether@gmail.com

**Comment by microsmith** [comment]
Are you an MCT? It might be better to post your question in the MCT forums: https://www.microsoft.com/en-us/learning/mct-central.aspx
