### ISSUE TITLE
Implementing Optimistic and Pessimistic Concurrency

### ISSUE THREAD

**Issue by debs1979** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#90]
Hi,
I am going to raise this ticket but it is not an issue. I want help with implementing the accesscondition check which we could do in v11 dll. But I am struggling to implement it using v12 dll. I know we can create the BlobRequestCondition for the same but I am not sure how to chck for ETAG in that class. Can a example be created for the same.

Thanks in Advance

**Comment by seesharprun** [comment]
I believe this is what you are looking for:

```csharp
var blobETagConditions = new BlobRequestConditions
{
    IfMatch = blobETag
};
await blob.UploadAsync(stream, conditions: blobETagConditions);
```
