### ISSUE TITLE
Invalid runtimeconfig.json error on lab 04

### ISSUE THREAD

**Issue by Incedo0808** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#91]
Hi 

What should be lab vm prerequisits related to dotnet core installation. I am working on my local development laptop for code related stuff and on lab04 at excercise 4: Migrating SQL data to Azure Cosmos DB. I have completed task1 (Create a migration project) but when doing task2(Create a .NET class) on dotnet run command I am getting below error. 
 **Invalid runtimeconfig.json [E:\Rajesh\Incedo\SimpliLearnAzure\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\Allfiles\Labs\04\Solution\AdventureWorks\AdventureWorks.Migrate\bin\Debug\netcoreapp3.0\AdventureWorks.Migrate.runtimeconfig.json] [E:\Rajesh\Incedo\SimpliLearnAzure\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\AZ-204-DevelopingSolutionsforMicrosoftAzure-master\Allfiles\Labs\04\Solution\AdventureWorks\AdventureWorks.Migrate\bin\Debug\netcoreapp3.0\AdventureWorks.Migrate.runtimeconfig.dev.json]** 

Please help to resolve this issue.

**Comment by seesharprun** [comment]
We have published a list of software installed on the vm at the [lab.md](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/lab.md) file.
