### ISSUE TITLE
Lab 1 should include how to do a build (compress-archive)

### ISSUE THREAD

**Issue by russgove** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#95]
# Module: 1
## Lab/Demo:1 
It would be really helful if this lab included instructuions on how to create the zip files that are deployed tpo azure.
I tried doing dotnet build then  a compress-archive from the bin\debug\dotnetcporeapp directory  of the imgweb app. after doing that and visiting the site I get an error You do not have 'permission to view this directory or page'

Repro steps:

1.dotnet build
2 cd .\bin\Debug\netcoreapp3.0\
3.  compress-archive  test.zip
4. deploy test.zip

**Comment by seesharprun** [comment]
We perform the build ahead of time to keep the lab length under the 45-minute maximum we set for the entire course.

For your notes, I am happy to share how we build that file.

1. Go to the **project folder** (not solution).
1. Run ``dotnet publish --configuration Debug --output out``.
1. Navigate to the newly created **out** folder.
1. Zip up the contents of the **out** folder.

That's how we built the zip files. When designing the lab, we found that having students build the zip files introduced two issues:
- The extra steps pushed the lab beyond 45 minutes
- If a student got any code incorrect, either the build would fail or the final application would fail

Having a clean zip file made sure every student could do the last half of the lab even if they made a mistake in the first half.

I hope this explanation helps.
-

**Comment by russgove** [comment]
Exactly what I was looking for! thank you.

**Comment by seesharprun** [comment]
Feel free to re-open the issue if you run into issues reproducing the zip files

**Comment by seesharprun** [comment]
One more note, we sometimes do a [self-contained build](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) if the versions of .NET on Azure App Service doesn't match up with our dev environment. To do that, we add the flag ``--self-contained`` to the end of the ``dotnet publish`` command.
