### ISSUE TITLE
Instruction should  say creat a Azure SQL Database Managed Instance to match whats in the porta;

### ISSUE THREAD

**Issue by russgove** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#97]
# Module: 4
### Task: 2

Instructions say  Create an Azure SQL Database server resource

in the portal it says  Create Azure SQL Database Managed Instance

instructions should say   Create an Azure SQL Database Managed Instance

**Comment by russgove** [comment]
also in this task the SQL passwords now need to be 16 Characters. The password in the instructions (TestPa55w.rd) dont work

**Comment by seesharprun** [comment]
For the first item, you want to create a SQL Database server. In the marketplace it's listed as "SQL server (logical server)" <https://portal.azure.com/#create/Microsoft.SQLServer>

![image](https://user-images.githubusercontent.com/5067401/89056114-7ea3b800-d329-11ea-8c79-d029ce6b5486.png)

**Comment by seesharprun** [comment]
For the second issue, I will work on updating the password. I will leave this issue open until the password is updated.

**Comment by russgove** [comment]
The password is fine for a SQL Server (logical server). I think the instructions should point out thet we need to create A SQL Server (logical  server).

Got it working now.  Thanks for your help.

**Comment by russgove** [comment]
SQL Server (Logical Server) is not even listed under Databases. Only way to get it is to know what its named and type its name explicitly into sthe search box :-(

**Comment by seesharprun** [comment]
That sounds like a discrepancy between the high-level instructions and the answer key. I checked out the answer key which had the correct instructions, but the high-level wasn’t specific enough.

**Comment by seesharprun** [comment]
Resolved in 0eed91f
