### ISSUE TITLE
Lab 12 - AddApplicationInsightsTelemetry Not Sending Data to AI

### ISSUE THREAD

**Issue by Farzaaaan** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#98]
#### Task: 02

Description of issue

using `services.AddApplicationInsightsTelemetry(INSTRUMENTATION_KEY)` in `ConfigureServices` method with `INSTRUMENTATION_KEY` as a variable does not send telemetry data to Application Insights.

Repro steps:

1. Follow lab steps by creating a private variable `INSTRUMENTATION_KEY`, and calling the `AddApplicationInsightsTelemetry(INSTRUMENTATION_KEY)` method in `ConfigureServices`
2. Run application either locally or deployed on an app service. Monitor the Application Insight instance expected to receive the data.

Solution: 

I followed the link below to resolve the issue by adding the instrumentation key to `appsettings.json`. 

https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

**Comment by seesharprun** [comment]
We were unable to reproduce this issue. The string variable worked fine.

If you read step 3 from the [Enable Application Insights server-side telemetry](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio) of the link you provided, it mentions that passing in a string argument to the ``AddApplicationInsightsTelemetry(string key)`` method will work.
